import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
export const islandRadius=22;
export function groundHeight(x:number,z:number){return .18*Math.sin(x*.32)*Math.cos(z*.28)+.065*Math.sin(x*.8+z*.65)}
export function exhibitPosition(i:number,total:number){const a=i/total*Math.PI*2;return new THREE.Vector3(Math.sin(a)*12,groundHeight(Math.sin(a)*12,Math.cos(a)*12),Math.cos(a)*12)}
function rng(seed:number){return()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}}
export async function buildEnvironment(scene:THREE.Scene,onProgress:(value:number)=>void){
 const random=rng(716);const loader=new GLTFLoader();const names=['CommonTree_1','CommonTree_3','TwistedTree_1','Bush_Common_Flowers','Fern_1','Flower_3_Group','Flower_4_Group','Rock_Medium_1','Rock_Medium_2','RockPath_Round_Wide','Mushroom_Common'];let done=0;
 const templates=new Map<string,THREE.Group>();const loaded=await Promise.allSettled(names.map(async name=>{const gltf=await loader.loadAsync(`/models/nature/${name}.gltf`);gltf.scene.traverse(o=>{if(o instanceof THREE.Mesh){o.castShadow=true;o.receiveShadow=true;const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>{if(m instanceof THREE.MeshStandardMaterial){m.roughness=.95;m.envMapIntensity=.35;if(m.alphaTest){m.side=THREE.DoubleSide;m.alphaTest=.45}}})}});templates.set(name,gltf.scene);onProgress(++done/names.length)}));
 const root=new THREE.Group();const collisionRoot=new THREE.Group();scene.add(root);let missing=0;loaded.forEach(r=>{if(r.status==='rejected')missing++});
 const plant=(name:string,x:number,z:number,height:number,rotation=random()*Math.PI*2)=>{const template=templates.get(name);if(!template)return;const object=template.clone(true);const box=new THREE.Box3().setFromObject(object),size=box.getSize(new THREE.Vector3());const scale=height/Math.max(size.y,.01);object.scale.setScalar(scale);object.position.set(x,groundHeight(x,z)-box.min.y*scale,z);object.rotation.y=rotation;object.traverse(o=>{if(o instanceof THREE.Mesh){o.userData.batch=true;const mats=Array.isArray(o.material)?o.material:[o.material];o.userData.solid=/Rock/.test(name)||mats.some(m=>/Bark/.test(m.name))}});root.add(object);return object};
 const blockers:{x:number;z:number;radius:number}[]=[];
 for(let i=0;i<26;i++){const angle=i/26*Math.PI*2+.12*random(),radius=17+random()*3;const x=Math.sin(angle)*radius,z=Math.cos(angle)*radius;plant(i%3?'CommonTree_1':'CommonTree_3',x,z,5.5+random()*4);blockers.push({x,z,radius:.65})}
 plant('TwistedTree_1',-5,-4,10);blockers.push({x:-5,z:-4,radius:1.2});
 for(let i=0;i<190;i++){const a=random()*Math.PI*2,r=14+random()*6,x=Math.cos(a)*r,z=Math.sin(a)*r;plant(['Bush_Common_Flowers','Fern_1','Flower_3_Group','Flower_4_Group','Mushroom_Common'][i%5],x,z,.25+random()*.85)}
 for(let i=0;i<25;i++){const a=random()*Math.PI*2,r=18+random()*3;plant(i%2?'Rock_Medium_1':'Rock_Medium_2',Math.cos(a)*r,Math.sin(a)*r,.7+random()*1.5)}
 // Paths wind around the meadow and branch toward the eight exhibits.
 for(let i=0;i<72;i++){const a=i/72*Math.PI*2;plant('RockPath_Round_Wide',Math.sin(a)*10,Math.cos(a)*10,.055+random()*.025,a)}
 for(let arm=0;arm<8;arm++){const a=arm/8*Math.PI*2;for(let i=1;i<10;i++){const r=i*1.1;plant('RockPath_Round_Wide',Math.sin(a)*r,Math.cos(a)*r,.05+random()*.025,a)}}
 const ground=new THREE.PlaneGeometry(44,44,150,150);ground.rotateX(-Math.PI/2);const p=ground.attributes.position;const colors=[];for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getZ(i);p.setY(i,groundHeight(x,z));const color=new THREE.Color().setHSL(.23+random()*.025,.28+random()*.15,.27+random()*.09);colors.push(color.r,color.g,color.b)}ground.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));const indices=[];const ix=ground.index!;for(let i=0;i<ix.count;i+=3){const a=ix.getX(i),b=ix.getX(i+1),c=ix.getX(i+2);if([a,b,c].every(v=>Math.hypot(p.getX(v),p.getZ(v))<islandRadius))indices.push(a,b,c)}ground.setIndex(indices);ground.computeVertexNormals();const terrain=new THREE.Mesh(ground,new THREE.MeshStandardMaterial({vertexColors:true,roughness:1}));terrain.userData.solid=true;terrain.receiveShadow=true;root.add(terrain);
 const rockMat=new THREE.MeshStandardMaterial({color:'#899188',roughness:1});const rockTex=new THREE.TextureLoader().load('/models/nature/Rocks_Diffuse.png');rockTex.colorSpace=THREE.SRGBColorSpace;rockTex.wrapS=rockTex.wrapT=THREE.RepeatWrapping;rockTex.repeat.set(4,2);rockMat.map=rockTex;
 const cliff=new THREE.CylinderGeometry(21.9,6,13,100,10,true);const cp=cliff.attributes.position;for(let i=0;i<cp.count;i++){const y=cp.getY(i),x=cp.getX(i),z=cp.getZ(i),a=Math.atan2(z,x);const noise=1+Math.sin(a*11+y*1.3)*.035+Math.cos(a*17-y*.7)*.025;cp.setXYZ(i,x*noise,y-6.6,z*noise)}cliff.computeVertexNormals();const cliffMesh=new THREE.Mesh(cliff,rockMat);root.add(cliffMesh);
 // Thousands of tapered grass blades, drawn in a single batch.
 const blade=new THREE.BufferGeometry();blade.setAttribute('position',new THREE.Float32BufferAttribute([-.04,0,0,.04,0,0,-.022,.22,.01,.022,.22,.01,0,.42,.045],3));blade.setIndex([0,1,2,1,3,2,2,3,4]);blade.computeVertexNormals();const grass=new THREE.InstancedMesh(blade,new THREE.MeshStandardMaterial({color:'#92aa52',side:THREE.DoubleSide,roughness:1}),6500);const dummy=new THREE.Object3D();for(let i=0;i<6500;i++){let x=0,z=0;do{x=(random()-.5)*42;z=(random()-.5)*42}while(Math.hypot(x,z)>21||Math.abs(Math.hypot(x,z)-10)<.65||Math.abs(Math.sin(Math.atan2(x,z)*4))*Math.hypot(x,z)<.55);dummy.position.set(x,groundHeight(x,z),z);dummy.rotation.y=random()*Math.PI;dummy.scale.setScalar(.55+random()*.7);dummy.updateMatrix();grass.setMatrixAt(i,dummy.matrix);grass.setColorAt(i,new THREE.Color().setHSL(.19+random()*.07,.35,.32+random()*.15))}grass.receiveShadow=true;root.add(grass);
 // Carved limestone pavilion: columns, capitals, layered cornice, and a golden astrolabe.
 const stone=new THREE.MeshStandardMaterial({color:'#ddd4bc',roughness:.86});const gold=new THREE.MeshStandardMaterial({color:'#cfaa58',metalness:.7,roughness:.35});const pavilion=new THREE.Group();pavilion.position.set(0,groundHeight(0,-7),-7);root.add(pavilion);
 const add=(geo:THREE.BufferGeometry,mat:THREE.Material,x:number,y:number,z:number,parent:THREE.Object3D=pavilion)=>{const m=new THREE.Mesh(geo,mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;if(mat===stone||mat===gold)m.userData.solid=true;parent.add(m);return m};
 for(let level=0;level<3;level++)add(new THREE.CylinderGeometry(3.1-level*.2,3.15-level*.2,.18,64),stone,0,level*.18,0);
 for(let i=0;i<6;i++){const a=i/6*Math.PI*2,x=Math.sin(a)*2.4,z=Math.cos(a)*2.4;add(new THREE.CylinderGeometry(.16,.21,3.1,24),stone,x,2.1,z);for(const h of [.65,.85,3.52,3.68])add(new THREE.CylinderGeometry(.28,.28,.13,24),stone,x,h,z);blockers.push({x,z:z-7,radius:.35})}
 for(let l=0;l<3;l++){const ring=add(new THREE.TorusGeometry(2.6+l*.08,.13,10,80),stone,0,3.8+l*.14,0);ring.rotation.x=Math.PI/2}
 const astro=new THREE.Group();astro.position.y=2.05;pavilion.add(astro);for(let i=0;i<3;i++){const torus=add(new THREE.TorusGeometry(.8+i*.08,.024,8,64),gold,0,0,0,astro);torus.rotation.set(i*.9,.5+i*.7,i*.6)}add(new THREE.SphereGeometry(.21,24,16),new THREE.MeshStandardMaterial({color:'#93daca',emissive:'#2fae92',emissiveIntensity:.8}),0,0,0,astro);
 // Shallow reflecting pool, a waterfall, and drifting luminous motes.
 const waterMaterial=new THREE.MeshPhysicalMaterial({color:'#75bfc3',metalness:.2,roughness:.16,transparent:true,opacity:.76,clearcoat:1});const pool=add(new THREE.CircleGeometry(2.5,80),waterMaterial,7,groundHeight(7,-2)+.025,-2,root);pool.rotation.x=-Math.PI/2;
 for(let i=0;i<19;i++){const a=i/19*Math.PI*2;plant('Rock_Medium_1',7+Math.cos(a)*2.7,-2+Math.sin(a)*2.7,.23+random()*.2)}
 const fall=add(new THREE.PlaneGeometry(1.5,12,8,20),new THREE.MeshStandardMaterial({color:'#a4e8e3',transparent:true,opacity:.5,side:THREE.DoubleSide,emissive:'#346b72',emissiveIntensity:.2}),12,-5.7,-17,root);fall.rotation.y=-.5;
 const motesGeo=new THREE.BufferGeometry();const motePos=[];for(let i=0;i<100;i++)motePos.push((random()-.5)*38,random()*4+.5,(random()-.5)*38);motesGeo.setAttribute('position',new THREE.Float32BufferAttribute(motePos,3));const motes=new THREE.Points(motesGeo,new THREE.PointsMaterial({color:'#fff4c5',size:.05,transparent:true,opacity:.8,depthWrite:false}));root.add(motes);
 for(let i=0;i<12;i++){const a=i/12*Math.PI*2,r=60+random()*50;const g=new THREE.SphereGeometry(12+random()*14,32,24);g.scale(1,1.5+random(),1);add(g,new THREE.MeshStandardMaterial({color:new THREE.Color().setHSL(.39,.12,.46),roughness:1}),Math.sin(a)*r,-15,Math.cos(a)*r,root)}
 root.updateMatrixWorld(true);
 root.traverse(o=>{if(o instanceof THREE.Mesh&&o.userData.solid){const proxy=new THREE.Mesh(o.geometry,o.material);proxy.matrix.copy(o.matrixWorld);proxy.matrixAutoUpdate=false;collisionRoot.add(proxy)}});
 const batches=new Map<string,{geometry:THREE.BufferGeometry;material:THREE.Material|THREE.Material[];objects:THREE.Mesh[]}>();root.traverse(o=>{if(o instanceof THREE.Mesh&&o.userData.batch){const key=o.geometry.uuid+':'+(Array.isArray(o.material)?o.material.map(m=>m.uuid).join(','):o.material.uuid);if(!batches.has(key))batches.set(key,{geometry:o.geometry,material:o.material,objects:[]});batches.get(key)!.objects.push(o)}});
 batches.forEach(({geometry,material,objects})=>{const batch=new THREE.InstancedMesh(geometry,material,objects.length);objects.forEach((o,i)=>{batch.setMatrixAt(i,o.matrixWorld);o.removeFromParent()});batch.castShadow=true;batch.receiveShadow=true;root.add(batch)});
 return {root,collisionRoot,blockers,missing,update(time:number){astro.rotation.y=time*.13;motes.rotation.y=time*.013;waterMaterial.opacity=.74+Math.sin(time*.8)*.04;fall.scale.x=1+Math.sin(time*1.8)*.035}};
}
