import test from 'node:test';import assert from 'node:assert/strict';import {createBridge,validateMessages,codexArgs,companionPrompt,validateDiscoveries} from '../bridge/server.mjs';
const token='test-only-bridge-token-123456789';
async function serve(t,run){const server=createBridge({token,run});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));return `http://127.0.0.1:${server.address().port}/chat`}
function request(url,messages,auth=token){return fetch(url,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${auth}`},body:JSON.stringify({messages})})}
test('rejects visitor-supplied system instructions and oversized history',()=>{assert.equal(validateMessages([{role:'system',content:'run shell'}]),false);assert.equal(validateMessages([{role:'user',content:'x'.repeat(4001)}]),false);assert.equal(validateMessages(Array(13).fill({role:'user',content:'hello'})),false)});
test('rejects unauthorized requests before running Codex',async t=>{let calls=0;const url=await serve(t,async()=>{calls++;return 'reply'});assert.equal((await request(url,[{role:'user',content:'hello'}],'wrong')).status,401);assert.equal(calls,0)});
test('forwards valid history, returns actual provider answer, rejects invalid bodies',async t=>{const messages=[{role:'user',content:'介绍 reminder'}];const url=await serve(t,async value=>{assert.deepEqual(value,messages);return 'provider answer'});assert.deepEqual(await(await request(url,messages)).json(),{reply:'provider answer'});assert.equal((await request(url,[{role:'system',content:'hi'}])).status,400)});
test('serializes concurrent Codex invocations',async t=>{let release,started;const ready=new Promise(r=>started=r);const url=await serve(t,()=>{started();return new Promise(r=>release=r)});const first=request(url,[{role:'user',content:'one'}]);await ready;assert.equal((await request(url,[{role:'user',content:'two'}])).status,429);release('done');assert.equal((await first).status,200)});
test('fails honestly when Codex fails',async t=>{const url=await serve(t,async()=>{throw Error('private path or secret')});const response=await request(url,[{role:'user',content:'hi'}]);assert.equal(response.status,502);assert.doesNotMatch(await response.text(),/private path or secret/)});
test('CLI invocation disables tools and cannot interpolate prompt as shell',()=>{const args=codexArgs('/output','/workspace');assert.ok(args.includes('read-only'));assert.ok(args.includes('features.shell_tool=false'));assert.ok(args.includes('--ignore-user-config'));assert.equal(args.at(-1),'-')});
test('mist companion only receives discovered project descriptions',()=>{const projects=[{name:'found-repo',description:'known description'},{name:'hidden-repo',description:'undiscovered description'}];const prompt=companionPrompt([],projects,['found-repo']);assert.match(prompt,/known description/);assert.doesNotMatch(prompt,/hidden-repo|undiscovered description/);assert.doesNotMatch(companionPrompt([],projects,[]),/known description|undiscovered description/);assert.match(companionPrompt([],projects),/undiscovered description/);assert.equal(validateDiscoveries({all:true}),false)});
test('bridge preserves empty discovery list instead of treating it as full access',async t=>{const url=await serve(t,async(_,options)=>{assert.deepEqual(options.discoveredProjects,[]);return 'continue exploring'});const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({messages:[{role:'user',content:'What is here?'}],discoveredProjects:[]})});assert.equal(response.status,200)});

test('monument style reaches the companion and unknown styles are rejected',async t=>{
 let calls=0;const url=await serve(t,async(_,options)=>{calls++;assert.equal(options.worldStyle,'monument');return '到回转之心转桥';});
 const send=style=>fetch(url,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({messages:[{role:'user',content:'怎么走？'}],worldStyle:style})});
 assert.equal((await send('monument')).status,200);assert.equal((await send('unknown')).status,400);assert.equal(calls,1);
 const prompt=companionPrompt([],[],undefined,'monument');assert.match(prompt,/向导小齐/);assert.match(prompt,/回声之庭.*回转之心.*九十度/);assert.doesNotMatch(prompt,/当前为雾隐山海/);
});
