import test from'node:test';
import assert from'node:assert/strict';
import{Vector3}from'three';
import{MistController,islandHeight,islandPosition,islandEntry,visibleIsland}from'../app/scene/mist-physics.mjs';
const still=new Vector3(),forward=new Vector3(0,0,-1),backward=new Vector3(0,0,1);
function advance(p,seconds,direction=still){for(let n=0;n<Math.round(seconds*120);n++)p.update(1/120,direction)}
test('idle player is carried by a moving island without sinking or accumulating velocity',()=>{const p=new MistController();for(let n=0;n<3600;n++){p.update(1/120,still);assert.ok(Math.abs(p.position.y-islandHeight(0,p.time))<.001);assert.equal(p.grounded,true)}assert.equal(p.respawns,0)});
test('forward and backward jumps reach adjacent independently moving islands',()=>{for(const start of [-4,0,3,9])for(const dir of [forward,backward]){const p=new MistController(start),origin=p.position.z;advance(p,.65,dir);p.requestJump();advance(p,.9,dir);advance(p,.6);assert.equal(p.checkpoint,start+(dir.z<0?1:-1),`start ${start}, dir ${dir.z}, z ${p.position.z-origin}`);assert.equal(p.grounded,true);assert.equal(p.respawns,0)}});
test('walking into the void returns to last landed island',()=>{const p=new MistController(3);for(let n=0;n<600&&!p.respawns;n++)p.update(1/120,forward);assert.equal(p.respawns,1);assert.equal(p.checkpoint,3);assert.deepEqual(p.position,islandPosition(3,p.time))});
test('jump can land back on the oscillating takeoff platform',()=>{const p=new MistController();p.requestJump();advance(p,1.4);assert.equal(p.grounded,true);assert.equal(p.island,0);assert.equal(p.respawns,0)});
test('explicit rescue restores the latest safe landing',()=>{const p=new MistController(-2);p.position.y=-8;p.velocity.set(1,-15,1);p.reset();assert.deepEqual(p.position,islandPosition(-2,p.time));assert.equal(p.velocity.length(),0)});
test('only current and immediate neighbor islands are visible',()=>{assert.deepEqual(Array.from({length:9},(_,i)=>i-4).filter(i=>visibleIsland(i,0)),[-1,0,1])});
test('inserting islands keeps stable project identities and empty wilderness has no endpoint',()=>{const route=[{id:'start',project:null},{id:'one',project:'repo-one'}];route.splice(1,0,{id:'new',project:'repo-new'});assert.equal(islandEntry(2,route).project,'repo-one');assert.equal(islandEntry(-100,route).project,null);assert.equal(islandEntry(100,route).project,null)});
test('new islands can be added behind the starting island',()=>{const route=[{id:'behind',project:'new-work'},{id:'arrival',project:null},{id:'ahead',project:'old-work'}];assert.equal(islandEntry(-1,route).project,'new-work');assert.equal(islandEntry(0,route).id,'arrival');assert.equal(islandEntry(1,route).project,'old-work')});
test('jump remains possible across different platform motion phases',()=>{for(let phase=0;phase<9;phase++){const p=new MistController(phase-4);advance(p,phase*.8);advance(p,.65,forward);p.requestJump();advance(p,.9,forward);advance(p,.6);assert.equal(p.checkpoint,phase-3,`phase ${phase}`);assert.equal(p.respawns,0)}});
