import test from 'node:test';import assert from 'node:assert/strict';
import * as THREE from 'three';
import {createCollisionWorld,PlayerController,safeCameraPosition,resolveFlyingBody} from '../app/scene/physics.mjs';
function scene(){const group=new THREE.Group();const floor=new THREE.Mesh(new THREE.BoxGeometry(50,.2,50));floor.position.y=-.1;group.add(floor);return group}
function box(group,x,y,z,w,h,d){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d));mesh.position.set(x,y,z);group.add(mesh);return mesh}
function settle(body){for(let i=0;i<120;i++)body.update(1/120,new THREE.Vector3())}
test('jump leaves the ground, obeys gravity, and lands without sinking',()=>{const world=createCollisionWorld(scene()),body=new PlayerController(world,new THREE.Vector3(0,0,0));settle(body);assert.ok(body.grounded);body.requestJump();let apex=0;for(let i=0;i<200;i++){body.update(1/120,new THREE.Vector3());apex=Math.max(apex,body.position.y);assert.ok(body.position.y>=-.002)}assert.ok(apex>1.8&&apex<1.95,`apex ${apex}`);assert.ok(body.grounded);assert.ok(Math.abs(body.position.y)<.005)});
test('thin wall blocks continuous input and long display frames',()=>{const group=scene();box(group,1,1.5,0,.06,3,6);const body=new PlayerController(createCollisionWorld(group),new THREE.Vector3());settle(body);for(let i=0;i<100;i++)body.update(.08,new THREE.Vector3(1,0,0));assert.ok(body.position.x<.62,`wall penetration x=${body.position.x}`);assert.ok(body.position.y>=-.005)});
test('jump hits a low ceiling instead of passing through it',()=>{const group=scene();box(group,0,2.45,0,5,.2,5);const body=new PlayerController(createCollisionWorld(group),new THREE.Vector3());settle(body);body.requestJump();let top=0;for(let i=0;i<200;i++){body.update(1/120,new THREE.Vector3());top=Math.max(top,body.position.y+body.height)}assert.ok(top<=2.351,`top=${top}`);assert.ok(body.grounded)});
test('lands on raised stone platform and can walk off it',()=>{const group=scene();box(group,0,.3,0,2,.6,2);const body=new PlayerController(createCollisionWorld(group),new THREE.Vector3(0,2,0));settle(body);assert.ok(Math.abs(body.position.y-.6)<.01);for(let i=0;i<180;i++)body.update(1/120,new THREE.Vector3(1,0,0));settle(body);assert.ok(Math.abs(body.position.y)<.01)});
test('camera retracts before geometry and flying body resolves intersections',()=>{const group=scene();box(group,0,1.5,2,4,3,.4);const world=createCollisionWorld(group);const camera=safeCameraPosition(world,new THREE.Vector3(0,1,0),new THREE.Vector3(0,1,5));assert.ok(camera.z<1.8);const p=resolveFlyingBody(world,new THREE.Vector3(0,1,1.75));assert.ok(p.z<=1.371,`flying body z=${p.z}`)});
test('corners and island edge remain bounded',()=>{const group=scene();box(group,1,1.5,0,.1,3,6);box(group,0,1.5,1,6,3,.1);const body=new PlayerController(createCollisionWorld(group),new THREE.Vector3());settle(body);for(let i=0;i<180;i++)body.update(1/60,new THREE.Vector3(1,0,1).normalize());assert.ok(body.position.x<.6&&body.position.z<.6);const edge=new PlayerController(createCollisionWorld(scene()),new THREE.Vector3(20,0,0));for(let i=0;i<180;i++)edge.update(1/60,new THREE.Vector3(1,0,0));assert.ok(edge.position.x<=20.701)});
test('walks up small stone steps without snapping through their surface',()=>{const group=scene();for(let i=0;i<3;i++)box(group,1+i*.7,.07+i*.07,0,.7,.14+i*.14,3);const body=new PlayerController(createCollisionWorld(group),new THREE.Vector3(-1,0,0));settle(body);let raised=false;for(let i=0;i<180;i++){body.update(1/120,new THREE.Vector3(1,0,0));if(body.position.y>.3)raised=true;}assert.ok(body.position.x>2,`stuck at ${body.position.x}`);assert.ok(raised)});
