'use client';
import{useEffect,useRef,useState}from'react';
import*as THREE from'three';
import projects from'../data/projects.json';
import route from'../data/mist-route.json';
import{loadCharacter,type Character,type CharacterProgress}from'./scene/characters';
import{mistStoneTextures,weatherCliff,addMistDetails}from'./scene/mist-scenery';
import{equipStaff}from'./scene/mist-staff';
import{dressMistTraveler}from'./scene/mist-outfit';
import type{WorldProps}from'./scene/world-styles';
import{MistController,islandPosition,islandEntry,visibleIsland}from'./scene/mist-physics.mjs';

export default function MistWorld(props:WorldProps){
 const host=useRef<HTMLDivElement>(null),current=useRef(props),touch=useRef(new Set<string>()),jump=useRef(false),returnToIsland=useRef(false);current.current=props;
 const[download,setDownload]=useState<CharacterProgress>({loaded:0,total:0,phase:'download'});
 const[loading,setLoading]=useState(true),[error,setError]=useState(''),[near,setNear]=useState(false),[notice,setNotice]=useState('向前移动并跳跃，空中再按一次可二段跳。');
 const investigate=useRef(()=>{});
 useEffect(()=>{
  setLoading(true);setDownload({loaded:0,total:0,phase:'download'});setError('');setNear(false);touch.current.clear();jump.current=false;
  const element=host.current!;let renderer:THREE.WebGLRenderer;
  try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'})}catch{setError('当前设备无法启动三维场景，请切换晴岚浮岛浏览作品。');setLoading(false);return}
  renderer.setPixelRatio(Math.min(devicePixelRatio,matchMedia('(pointer: coarse)').matches?1:1.5));renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.95;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;element.appendChild(renderer.domElement);
  const scene=new THREE.Scene();scene.background=new THREE.Color('#77756b');scene.fog=new THREE.Fog('#77756b',7,22);
  scene.add(new THREE.HemisphereLight('#c4c3b3','#20231f',1.1));
  const sun=new THREE.DirectionalLight('#ead5a8',3.2);sun.position.set(-7,16,5);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-14,right:14,top:14,bottom:-14,near:.5,far:50});sun.shadow.normalBias=.06;scene.add(sun,sun.target);
  const camera=new THREE.PerspectiveCamera(52,1,.1,55),target=new THREE.Vector3(),desired=new THREE.Vector3();let yaw=0,pitch=.26,distance=6.7;
  const controller=new MistController(),player=new THREE.Group();scene.add(player);player.position.copy(controller.position);player.rotation.y=Math.PI;
  let outfit:ReturnType<typeof dressMistTraveler>|undefined;
  let avatar:Character|undefined,disposed=false,ready=false,frame=0,last=performance.now(),nearby=false,anchor=0,respawns=0,lastPlayer='',noticeUntil=6;
  const rockTextures=mistStoneTextures(()=>{if(!disposed)setError('石材细节暂未加载，不影响探索。')});
  const stone=new THREE.MeshStandardMaterial({color:'#a29b86',map:rockTextures.color,normalMap:rockTextures.normal,normalScale:new THREE.Vector2(.75,.75),roughness:.92}),dark=new THREE.MeshStandardMaterial({color:'#716b5d',map:rockTextures.color,normalMap:rockTextures.normal,roughness:.97}),edge=new THREE.MeshStandardMaterial({color:'#99917b',map:rockTextures.color,normalMap:rockTextures.normal,roughness:.95}),gold=new THREE.MeshStandardMaterial({color:'#c99d50',emissive:'#b36e26',emissiveIntensity:.5,roughness:.65}),bark=new THREE.MeshStandardMaterial({color:'#292e28',roughness:1});
  const geometries=new Set<THREE.BufferGeometry>(),materials=new Set<THREE.Material>([stone,dark,edge,gold,bark]);
  function mesh(geometry:THREE.BufferGeometry,material:THREE.Material,parent:THREE.Object3D,x=0,y=0,z=0){geometries.add(geometry);const object=new THREE.Mesh(geometry,material);object.position.set(x,y,z);object.castShadow=true;object.receiveShadow=true;parent.add(object);return object}
  function random(seed:number){const x=Math.sin(seed*127.1+311.7)*43758.5453;return x-Math.floor(x)}
  const fogCanvas=document.createElement('canvas');fogCanvas.width=fogCanvas.height=64;const ctx=fogCanvas.getContext('2d')!,gradient=ctx.createRadialGradient(32,32,0,32,32,32);gradient.addColorStop(0,'#c1cbb68c');gradient.addColorStop(.4,'#a5b39d32');gradient.addColorStop(1,'#a5b39d00');ctx.fillStyle=gradient;ctx.fillRect(0,0,64,64);const fogTexture=new THREE.CanvasTexture(fogCanvas),fogMaterial=new THREE.SpriteMaterial({map:fogTexture,transparent:true,opacity:.32,depthWrite:false});materials.add(fogMaterial);
  type Island={root:THREE.Group;relic:THREE.Group;clouds:THREE.Sprite[];owned:THREE.Material[]};const islands=new Map<number,Island>();
  function makeIsland(index:number){
   const root=new THREE.Group();scene.add(root);const seed=index*19+101;
   mesh(new THREE.CylinderGeometry(3.6,3.57,.16,64),stone,root,0,-.08);mesh(weatherCliff(),dark,root);
   for(const side of [-1,1]){mesh(new THREE.CylinderGeometry(.16,.25,1.2,12),dark,root,side*2.6,.6,.6);mesh(new THREE.BoxGeometry(.5,.12,.5),edge,root,side*2.6,1.25,.6);mesh(new THREE.SphereGeometry(.065,8,6),gold,root,side*2.6,1.5,.6)}
   const details=addMistDetails(root,index,mesh,stone,dark,gold);const owned=details.materials;owned.forEach(m=>materials.add(m));
   root.traverse(o=>{if(o instanceof THREE.LineSegments){geometries.add(o.geometry);const mats=Array.isArray(o.material)?o.material:[o.material];owned.push(...mats);mats.forEach(m=>materials.add(m))}});
   const relic=new THREE.Group();relic.position.set(1.3,.6,-.65);root.add(relic);mesh(new THREE.CylinderGeometry(.55,.62,.22,8),dark,relic,0,-.48);const tablet=mesh(new THREE.BoxGeometry(.48,.63,.12),stone,relic);tablet.rotation.z=.08;for(let j=0;j<3;j++)mesh(new THREE.BoxGeometry(.19-j*.025,.018,.008),gold,relic,0,.15-j*.13,.067);
   const clouds:THREE.Sprite[]=[];for(let j=0;j<6;j++){const cloud=new THREE.Sprite(fogMaterial);cloud.position.set((random(seed+j*7)-.5)*12,-1.4+random(seed+j*13)*1.7,(random(seed+j*9)-.5)*12);cloud.scale.set(8,3.2,1);root.add(cloud);clouds.push(cloud)}
   return{root,relic,clouds,owned};
  }
  function syncIslands(){for(let index=anchor-2;index<=anchor+2;index++)if(!islands.has(index))islands.set(index,makeIsland(index));for(const[index,island]of islands)if(Math.abs(index-anchor)>2){scene.remove(island.root);island.root.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.LineSegments){o.geometry.dispose();geometries.delete(o.geometry)}});island.owned.forEach(m=>{m.dispose();materials.delete(m)});islands.delete(index)}}syncIslands();
  function disposeCharacter(character:Character){character.root.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();for(const material of Array.isArray(o.material)?o.material:[o.material]){for(const value of Object.values(material))if(value instanceof THREE.Texture)value.dispose();material.dispose()}}})}
  loadCharacter(false,props.playerSource,true,value=>{if(!disposed)setDownload(value)}).then(c=>{if(disposed){disposeCharacter(c);return}avatar=c;outfit=dressMistTraveler(c.vrm,false);equipStaff(c.vrm);player.add(c.root);ready=true;setLoading(false)}).catch(()=>{if(!disposed){setLoading(false);setError('人物暂未加载成功，可以在角色形象中重新选择。')}});
  investigate.current=()=>{if(!nearby||current.current.paused)return;const entry=islandEntry(controller.island,route),index=projects.findIndex(p=>p.name===entry.project);if(index>=0)current.current.onSelect(index);else{setNotice('石上无字，唯有风声。再往前看看。');noticeUntil=controller.time+5}};
  const keys=new Set<string>();let down:{x:number;y:number;startX:number;startY:number}|null=null,dragged=false;const direction=new THREE.Vector3(),follow=new THREE.Vector3();
  const clear=()=>{keys.clear();touch.current.clear();jump.current=false;down=null};
  const keydown=(e:KeyboardEvent)=>{if(current.current.paused||/INPUT|TEXTAREA|SELECT/.test((e.target as HTMLElement).tagName))return;const key=e.key.length===1?e.key.toLowerCase():e.key;if(['w','a','s','d','ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','e'].includes(key)){e.preventDefault();if(key===' '&&!e.repeat)jump.current=true;else if(key==='e'&&!e.repeat)investigate.current();else keys.add(key)}};
  const keyup=(e:KeyboardEvent)=>keys.delete(e.key.length===1?e.key.toLowerCase():e.key);
  const start=(e:PointerEvent)=>{if(current.current.paused)return;down={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY};dragged=false;renderer.domElement.setPointerCapture(e.pointerId)};
  const move=(e:PointerEvent)=>{if(!down||current.current.paused)return;if(Math.hypot(e.clientX-down.startX,e.clientY-down.startY)>4)dragged=true;if(dragged){yaw-=(e.clientX-down.x)*.005;pitch=THREE.MathUtils.clamp(pitch+(e.clientY-down.y)*.003,.08,.65)}down.x=e.clientX;down.y=e.clientY};
  const stop=(e:PointerEvent)=>{if(down&&!dragged&&!current.current.paused){const rect=element.getBoundingClientRect(),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const altar=islands.get(controller.island)?.relic;if(altar&&ray.intersectObject(altar,true).length)investigate.current()}down=null};
  const wheel=(e:WheelEvent)=>{if(!current.current.paused)distance=THREE.MathUtils.clamp(distance+e.deltaY*.005,4.5,8)};
  const resize=()=>{renderer.setSize(element.clientWidth,element.clientHeight);camera.aspect=element.clientWidth/element.clientHeight;camera.updateProjectionMatrix()};const observer=new ResizeObserver(resize);observer.observe(element);resize();
  window.addEventListener('keydown',keydown);window.addEventListener('keyup',keyup);window.addEventListener('blur',clear);document.addEventListener('visibilitychange',clear);renderer.domElement.addEventListener('pointerdown',start);renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointerup',stop);renderer.domElement.addEventListener('pointercancel',clear);renderer.domElement.addEventListener('wheel',wheel,{passive:true});
  camera.position.copy(player.position).add(new THREE.Vector3(0,3,7));target.copy(player.position).y+=1.3;let wasPaused=false;
  function loop(now:number){const dt=Math.min((now-last)/1000,.08);last=now;const state=current.current,paused=state.paused||document.hidden||!ready;if(paused&&!wasPaused)clear();wasPaused=paused;
   if(avatar&&lastPlayer!==state.playerAppearance){avatar.setAppearance(state.playerAppearance);lastPlayer=state.playerAppearance}
   let turn=0;direction.set(0,0,0);if(!paused){const held=(key:string,arrow:string)=>keys.has(key)||keys.has(arrow)||touch.current.has(key);direction.set(Number(held('d','ArrowRight'))-Number(held('a','ArrowLeft')),0,Number(held('s','ArrowDown'))-Number(held('w','ArrowUp'))).normalize().applyAxisAngle(THREE.Object3D.DEFAULT_UP,yaw);if(jump.current){controller.requestJump();jump.current=false}if(returnToIsland.current){controller.reset();returnToIsland.current=false}player.position.copy(controller.update(dt,direction));if(Math.hypot(controller.velocity.x,controller.velocity.z)>.12){const heading=Math.atan2(controller.velocity.x,controller.velocity.z);const angle=Math.atan2(Math.sin(heading-player.rotation.y),Math.cos(heading-player.rotation.y));const rotation=THREE.MathUtils.clamp(angle,-dt*6,dt*6);player.rotation.y+=rotation;turn=rotation/Math.max(dt,.001)/6}}
   if(controller.checkpoint!==anchor){anchor=controller.checkpoint;syncIslands()}if(controller.respawns!==respawns){respawns=controller.respawns;clear();setNotice('风把你送回了最近落脚的岛。');noticeUntil=controller.time+4;target.copy(player.position).y+=1.3;camera.position.copy(target).add(new THREE.Vector3(0,2,6))}
   const time=controller.time;for(const[index,island]of islands){island.root.position.copy(islandPosition(index,time));island.root.visible=visibleIsland(index,anchor);island.clouds.forEach((cloud,j)=>{cloud.position.x=Math.sin(time*.13+index+j)*4;cloud.material.rotation=Math.sin(time*.05+j)*.1})}
   const close=controller.grounded&&Math.hypot(player.position.x-islandPosition(controller.island,time).x-1.3,player.position.z+controller.island*8.4+.65)<1.65;if(close!==nearby){nearby=close;setNear(close)}if(noticeUntil&&time>noticeUntil){setNotice('');noticeUntil=0}
   avatar?.update(paused?0:dt,time,{speed:paused?0:Math.hypot(controller.velocity.x,controller.velocity.z)/4.4,metersPerSecond:Math.hypot(controller.velocity.x,controller.velocity.z),grounded:controller.grounded,verticalVelocity:controller.velocity.y,landing:controller.landing,turn,engaged:false});
   outfit?.update(paused?0:dt,Math.hypot(controller.velocity.x,controller.velocity.z)/4.4,turn);
   follow.copy(player.position);follow.y+=1.3;target.lerp(follow,1-Math.exp(-8*dt));desired.set(target.x+Math.sin(yaw)*Math.cos(pitch)*distance,target.y+Math.sin(pitch)*distance,target.z+Math.cos(yaw)*Math.cos(pitch)*distance);camera.position.lerp(desired,1-Math.exp(-9*dt));camera.lookAt(target);sun.position.copy(player.position).add(new THREE.Vector3(-7,16,5));sun.target.position.copy(player.position);if(!document.hidden)renderer.render(scene,camera);frame=requestAnimationFrame(loop)
  }frame=requestAnimationFrame(loop);
  return()=>{disposed=true;cancelAnimationFrame(frame);observer.disconnect();clear();window.removeEventListener('keydown',keydown);window.removeEventListener('keyup',keyup);window.removeEventListener('blur',clear);document.removeEventListener('visibilitychange',clear);renderer.domElement.removeEventListener('pointerdown',start);renderer.domElement.removeEventListener('pointermove',move);renderer.domElement.removeEventListener('pointerup',stop);renderer.domElement.removeEventListener('pointercancel',clear);renderer.domElement.removeEventListener('wheel',wheel);if(avatar)disposeCharacter(avatar);geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());fogTexture.dispose();rockTextures.color.dispose();rockTextures.normal.dispose();renderer.dispose();renderer.domElement.remove()};
 },[props.playerSource]);
 return <><div className="world" ref={host} aria-label="可跳跃探索的迷雾浮岛"/>{loading&&<div className="scene-loading-note" role="status"><span>山海已至 · 旅行者正在赶来</span><div className="asset-progress" role="progressbar" aria-label="旅行者下载进度" aria-valuemin={0} aria-valuemax={100} aria-valuenow={download.total&&download.phase==='download'?Math.min(100,Math.floor(download.loaded/download.total*100)):undefined}><i className={!download.total||download.phase!=='download'?'indeterminate':''} style={{width:download.phase==='download'&&download.total?`${Math.min(100,download.loaded/download.total*100)}%`:undefined}}/></div><small>{download.phase==='download'?(download.total?`${Math.min(100,Math.floor(download.loaded/download.total*100))}% · ${(download.loaded/1048576).toFixed(1)} / ${(download.total/1048576).toFixed(1)} MB`:`已下载 ${(download.loaded/1048576).toFixed(1)} MB`):download.phase==='decode'?'下载完成 · 正在解压':'下载完成 · 正在准备人物与握持动作'}</small></div>}{error&&<p className="asset-warning" role="alert">{error}</p>}{!loading&&!props.paused&&<><button className="view-toggle" onClick={()=>{returnToIsland.current=true}}>返回落脚处 ↺</button>{notice&&<p className="mist-notice" role="status">{notice}</p>}{near&&<button className="near-prompt" onClick={()=>investigate.current()}><kbd>E</kbd> 调查石碑</button>}<button className="jump-button" aria-label="跳跃，空中再按一次二段跳" title="空中再按一次，可二段跳" onClick={()=>{jump.current=true}}>二段跳 <kbd>Space</kbd></button><div className="touch-controls" role="group" aria-label="角色移动">{[['w','↑','向前'],['a','←','向左'],['s','↓','向后'],['d','→','向右']].map(([key,arrow,label])=><button key={key} className={`move-${key}`} aria-label={label} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);touch.current.add(key)}} onPointerUp={()=>touch.current.delete(key)} onPointerCancel={()=>touch.current.delete(key)} onLostPointerCapture={()=>touch.current.delete(key)}>{arrow}</button>)}</div></>}</>
}
