'use client';
import{useEffect,useRef,useState}from'react';
import*as THREE from'three';
import projects from'../data/projects.json';
import route from'../data/mist-route.json';
import{loadCharacter,type Character}from'./scene/characters';
import type{WorldProps}from'./scene/world-styles';
import{MistController,islandPosition,islandEntry,visibleIsland}from'./scene/mist-physics.mjs';

export default function MistWorld(props:WorldProps){
 const host=useRef<HTMLDivElement>(null),current=useRef(props),touch=useRef(new Set<string>()),jump=useRef(false),returnToIsland=useRef(false);current.current=props;
 const[loading,setLoading]=useState(true),[error,setError]=useState(''),[near,setNear]=useState(false),[notice,setNotice]=useState('沿石阶走向岛缘，向前移动并跳跃。');
 const investigate=useRef(()=>{});
 useEffect(()=>{
  setLoading(true);setError('');setNear(false);touch.current.clear();jump.current=false;
  const element=host.current!;let renderer:THREE.WebGLRenderer;
  try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'})}catch{setError('当前设备无法启动三维场景，请切换晴岚浮岛浏览作品。');setLoading(false);return}
  renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.9;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;element.appendChild(renderer.domElement);
  const scene=new THREE.Scene();scene.background=new THREE.Color('#545c59');scene.fog=new THREE.Fog('#545c59',5.5,21);
  scene.add(new THREE.HemisphereLight('#cbd3c6','#182622',2));
  const sun=new THREE.DirectionalLight('#ece0bd',2.1);sun.position.set(-7,16,5);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-14,right:14,top:14,bottom:-14,near:.5,far:50});sun.shadow.normalBias=.06;scene.add(sun,sun.target);
  const camera=new THREE.PerspectiveCamera(52,1,.1,55),target=new THREE.Vector3(),desired=new THREE.Vector3();let yaw=0,pitch=.26,distance=6.7;
  const controller=new MistController(),player=new THREE.Group(),fairyRoot=new THREE.Group();scene.add(player,fairyRoot);player.position.copy(controller.position);player.rotation.y=Math.PI;fairyRoot.position.copy(player.position).add(new THREE.Vector3(1.1,1.7,.3));
  let avatar:Character|undefined,fairy:Character|undefined,disposed=false,ready=false,frame=0,last=performance.now(),nearby=false,anchor=0,respawns=0,lastPlayer='',lastFairy='',noticeUntil=6;
  const stone=new THREE.MeshStandardMaterial({color:'#5c6258',roughness:1,flatShading:true}),dark=new THREE.MeshStandardMaterial({color:'#292f2a',roughness:1,flatShading:true}),edge=new THREE.MeshStandardMaterial({color:'#77776a',roughness:1}),gold=new THREE.MeshStandardMaterial({color:'#c99d50',emissive:'#b36e26',emissiveIntensity:.5,roughness:.65}),bark=new THREE.MeshStandardMaterial({color:'#292e28',roughness:1});
  const geometries=new Set<THREE.BufferGeometry>(),materials=new Set<THREE.Material>([stone,dark,edge,gold,bark]);
  function mesh(geometry:THREE.BufferGeometry,material:THREE.Material,parent:THREE.Object3D,x=0,y=0,z=0){geometries.add(geometry);const object=new THREE.Mesh(geometry,material);object.position.set(x,y,z);object.castShadow=true;object.receiveShadow=true;parent.add(object);return object}
  function random(seed:number){const x=Math.sin(seed*127.1+311.7)*43758.5453;return x-Math.floor(x)}
  const fogCanvas=document.createElement('canvas');fogCanvas.width=fogCanvas.height=64;const ctx=fogCanvas.getContext('2d')!,gradient=ctx.createRadialGradient(32,32,0,32,32,32);gradient.addColorStop(0,'#c1cbb68c');gradient.addColorStop(.4,'#a5b39d32');gradient.addColorStop(1,'#a5b39d00');ctx.fillStyle=gradient;ctx.fillRect(0,0,64,64);const fogTexture=new THREE.CanvasTexture(fogCanvas),fogMaterial=new THREE.SpriteMaterial({map:fogTexture,transparent:true,opacity:.32,depthWrite:false});materials.add(fogMaterial);
  type Island={root:THREE.Group;relic:THREE.Group;clouds:THREE.Sprite[]};const islands=new Map<number,Island>();
  function makeIsland(index:number){
   const root=new THREE.Group();scene.add(root);const seed=index*19+101;
   mesh(new THREE.CylinderGeometry(3.6,3.3,.65,48),stone,root,0,-.325);mesh(new THREE.CylinderGeometry(3.35,2.25,1.25,11),dark,root,0,-1.2);mesh(new THREE.ConeGeometry(2.3,3.4,9),dark,root,0,-3.05).rotation.z=Math.PI;
   const rim=mesh(new THREE.TorusGeometry(3.48,.07,6,64),edge,root,0,.02);rim.rotation.x=Math.PI/2;
   // A continuous level landing surface with broken paving and low relief.
   for(let j=0;j<15;j++){const a=j*2.4,r=.65+random(seed+j)*2.55;const tile=mesh(new THREE.CylinderGeometry(.36,.4,.035,5),j%3?stone:edge,root,Math.cos(a)*r,.018,Math.sin(a)*r);tile.rotation.y=a}
   for(const side of [-1,1]){for(let j=0;j<3;j++)mesh(new THREE.BoxGeometry(1.25,.025,.32),edge,root,0,.022,side*(2.25+j*.35));const pillar=mesh(new THREE.CylinderGeometry(.16,.25,1.2,8),dark,root,side*2.6,.6,.6);pillar.rotation.z=side*.08;mesh(new THREE.BoxGeometry(.5,.12,.5),edge,root,side*2.65,1.25,.6);mesh(new THREE.SphereGeometry(.085,8,6),gold,root,side*2.65,1.4,.6)}
   // Weathered tree silhouettes stay outside the walkable landing disk.
   const tree=new THREE.Group();tree.position.set(index%2?3.8:-3.8,-.1,.4);tree.rotation.z=index%2?-.22:.22;root.add(tree);mesh(new THREE.CylinderGeometry(.07,.22,2.4,7),bark,tree,0,1.1);for(let j=0;j<4;j++){const branch=mesh(new THREE.CylinderGeometry(.025,.065,1.4,5),bark,tree,(j%2?1:-1)*.35,1.1+j*.36,0);branch.rotation.z=(j%2?1:-1)*.8}
   const relic=new THREE.Group();relic.position.set(1.3,.6,-.65);root.add(relic);mesh(new THREE.CylinderGeometry(.55,.62,.22,8),dark,relic,0,-.48);const tablet=mesh(new THREE.BoxGeometry(.48,.63,.12),stone,relic);tablet.rotation.z=.08;for(let j=0;j<3;j++)mesh(new THREE.BoxGeometry(.19-j*.025,.018,.008),gold,relic,0,.15-j*.13,.067);
   const clouds:THREE.Sprite[]=[];for(let j=0;j<6;j++){const cloud=new THREE.Sprite(fogMaterial);cloud.position.set((random(seed+j*7)-.5)*12,-1.4+random(seed+j*13)*1.7,(random(seed+j*9)-.5)*12);cloud.scale.set(8,3.2,1);root.add(cloud);clouds.push(cloud)}
   return{root,relic,clouds};
  }
  function syncIslands(){for(let index=anchor-2;index<=anchor+2;index++)if(!islands.has(index))islands.set(index,makeIsland(index));for(const[index,island]of islands)if(Math.abs(index-anchor)>2){scene.remove(island.root);island.root.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();geometries.delete(o.geometry)}});islands.delete(index)}}syncIslands();
  function disposeCharacter(character:Character){character.root.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();for(const material of Array.isArray(o.material)?o.material:[o.material]){for(const value of Object.values(material))if(value instanceof THREE.Texture)value.dispose();material.dispose()}}})}
  Promise.allSettled([loadCharacter(false,props.playerSource).then(c=>{if(disposed){disposeCharacter(c);return}avatar=c;player.add(c.root)}),loadCharacter(true,props.companionSource).then(c=>{if(disposed){disposeCharacter(c);return}fairy=c;fairyRoot.add(c.root)})]).then(results=>{if(disposed)return;ready=true;setLoading(false);if(results.some(r=>r.status==='rejected'))setError('人物暂未加载成功，可以在角色形象中重新选择。')});
  investigate.current=()=>{if(!nearby||current.current.paused)return;const entry=islandEntry(controller.island,route),index=projects.findIndex(p=>p.name===entry.project);if(index>=0)current.current.onSelect(index);else{setNotice('石上无字，唯有风声。再往前看看。');noticeUntil=controller.time+5}};
  const keys=new Set<string>();let down:{x:number;y:number;startX:number;startY:number}|null=null,dragged=false;const direction=new THREE.Vector3(),follow=new THREE.Vector3();
  const clear=()=>{keys.clear();touch.current.clear();jump.current=false;down=null};
  const keydown=(e:KeyboardEvent)=>{if(current.current.paused||/INPUT|TEXTAREA|SELECT/.test((e.target as HTMLElement).tagName))return;const key=e.key.length===1?e.key.toLowerCase():e.key;if(['w','a','s','d','ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','e'].includes(key)){e.preventDefault();if(key===' '&&!e.repeat)jump.current=true;else if(key==='e'&&!e.repeat)investigate.current();else keys.add(key)}};
  const keyup=(e:KeyboardEvent)=>keys.delete(e.key.length===1?e.key.toLowerCase():e.key);
  const start=(e:PointerEvent)=>{if(current.current.paused)return;down={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY};dragged=false;renderer.domElement.setPointerCapture(e.pointerId)};
  const move=(e:PointerEvent)=>{if(!down||current.current.paused)return;if(Math.hypot(e.clientX-down.startX,e.clientY-down.startY)>4)dragged=true;if(dragged){yaw-=(e.clientX-down.x)*.005;pitch=THREE.MathUtils.clamp(pitch+(e.clientY-down.y)*.003,.08,.65)}down.x=e.clientX;down.y=e.clientY};
  const stop=(e:PointerEvent)=>{if(down&&!dragged&&!current.current.paused){const rect=element.getBoundingClientRect(),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const altar=islands.get(controller.island)?.relic;if(altar&&ray.intersectObject(altar,true).length)investigate.current();else if(ray.intersectObject(fairyRoot,true).length)current.current.onChat()}down=null};
  const wheel=(e:WheelEvent)=>{if(!current.current.paused)distance=THREE.MathUtils.clamp(distance+e.deltaY*.005,4.5,8)};
  const resize=()=>{renderer.setSize(element.clientWidth,element.clientHeight);camera.aspect=element.clientWidth/element.clientHeight;camera.updateProjectionMatrix()};const observer=new ResizeObserver(resize);observer.observe(element);resize();
  window.addEventListener('keydown',keydown);window.addEventListener('keyup',keyup);window.addEventListener('blur',clear);document.addEventListener('visibilitychange',clear);renderer.domElement.addEventListener('pointerdown',start);renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointerup',stop);renderer.domElement.addEventListener('pointercancel',clear);renderer.domElement.addEventListener('wheel',wheel,{passive:true});
  camera.position.copy(player.position).add(new THREE.Vector3(0,3,7));target.copy(player.position).y+=1.3;let wasPaused=false;
  function loop(now:number){const dt=Math.min((now-last)/1000,.04);last=now;const state=current.current,paused=state.paused||document.hidden||!ready;if(paused&&!wasPaused)clear();wasPaused=paused;
   if(avatar&&lastPlayer!==state.playerAppearance){avatar.setAppearance(state.playerAppearance);lastPlayer=state.playerAppearance}if(fairy&&lastFairy!==state.companionAppearance){fairy.setAppearance(state.companionAppearance);lastFairy=state.companionAppearance}
   let turn=0;direction.set(0,0,0);if(!paused){const held=(key:string,arrow:string)=>keys.has(key)||keys.has(arrow)||touch.current.has(key);direction.set(Number(held('d','ArrowRight'))-Number(held('a','ArrowLeft')),0,Number(held('s','ArrowDown'))-Number(held('w','ArrowUp'))).normalize().applyAxisAngle(THREE.Object3D.DEFAULT_UP,yaw);if(jump.current){controller.requestJump();jump.current=false}if(returnToIsland.current){controller.reset();returnToIsland.current=false}player.position.copy(controller.update(dt,direction));if(direction.lengthSq()>.01){const heading=Math.atan2(direction.x,direction.z);turn=Math.atan2(Math.sin(heading-player.rotation.y),Math.cos(heading-player.rotation.y));player.rotation.y+=turn*(1-Math.exp(-10*dt))}}
   if(controller.checkpoint!==anchor){anchor=controller.checkpoint;syncIslands()}if(controller.respawns!==respawns){respawns=controller.respawns;clear();setNotice('风把你送回了最近落脚的岛。');noticeUntil=controller.time+4;target.copy(player.position).y+=1.3;camera.position.copy(target).add(new THREE.Vector3(0,2,6));fairyRoot.position.copy(player.position).add(new THREE.Vector3(1,1.6,0))}
   const time=controller.time;for(const[index,island]of islands){island.root.position.copy(islandPosition(index,time));island.root.visible=visibleIsland(index,anchor);island.clouds.forEach((cloud,j)=>{cloud.position.x=Math.sin(time*.13+index+j)*4;cloud.material.rotation=Math.sin(time*.05+j)*.1})}
   const close=controller.grounded&&Math.hypot(player.position.x-islandPosition(controller.island,time).x-1.3,player.position.z+controller.island*8.4+.65)<1.65;if(close!==nearby){nearby=close;setNear(close)}if(noticeUntil&&time>noticeUntil){setNotice('');noticeUntil=0}
   avatar?.update(paused?0:dt,time,{speed:paused?0:Math.hypot(controller.velocity.x,controller.velocity.z)/4.4,grounded:controller.grounded,verticalVelocity:controller.velocity.y,landing:controller.landing,turn,engaged:false});
   follow.set(1.15,1.65+Math.sin(time*2)*.13,.3).applyAxisAngle(THREE.Object3D.DEFAULT_UP,player.rotation.y).add(player.position);fairyRoot.position.lerp(follow,1-Math.exp(-5*dt));fairyRoot.rotation.y=player.rotation.y;fairy?.update(paused?0:dt,time,{speed:paused?0:Math.min(1,controller.velocity.length()/4.4),grounded:false,verticalVelocity:0,landing:0,turn,engaged:state.chatOpen});
   follow.copy(player.position);follow.y+=1.3;target.lerp(follow,1-Math.exp(-8*dt));desired.set(target.x+Math.sin(yaw)*Math.cos(pitch)*distance,target.y+Math.sin(pitch)*distance,target.z+Math.cos(yaw)*Math.cos(pitch)*distance);camera.position.lerp(desired,1-Math.exp(-9*dt));camera.lookAt(target);sun.position.copy(player.position).add(new THREE.Vector3(-7,16,5));sun.target.position.copy(player.position);if(!document.hidden)renderer.render(scene,camera);frame=requestAnimationFrame(loop)
  }frame=requestAnimationFrame(loop);
  return()=>{disposed=true;cancelAnimationFrame(frame);observer.disconnect();clear();window.removeEventListener('keydown',keydown);window.removeEventListener('keyup',keyup);window.removeEventListener('blur',clear);document.removeEventListener('visibilitychange',clear);renderer.domElement.removeEventListener('pointerdown',start);renderer.domElement.removeEventListener('pointermove',move);renderer.domElement.removeEventListener('pointerup',stop);renderer.domElement.removeEventListener('pointercancel',clear);renderer.domElement.removeEventListener('wheel',wheel);if(avatar)disposeCharacter(avatar);if(fairy)disposeCharacter(fairy);geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());fogTexture.dispose();renderer.dispose();renderer.domElement.remove()};
 },[props.playerSource,props.companionSource]);
 return <><div className="world" ref={host} aria-label="可跳跃探索的迷雾浮岛"/>{loading&&<div className="world-loading" role="status"><span>雾起，山海渐近</span><small>正在唤醒旅行者与小齐…</small></div>}{error&&<p className="asset-warning" role="alert">{error}</p>}{!loading&&!props.paused&&<><button className="view-toggle" onClick={()=>{returnToIsland.current=true}}>返回落脚处 ↺</button>{notice&&<p className="mist-notice" role="status">{notice}</p>}{near&&<button className="near-prompt" onClick={()=>investigate.current()}><kbd>E</kbd> 调查石碑</button>}<button className="jump-button" aria-label="跳跃" onClick={()=>{jump.current=true}}>跳跃 <kbd>Space</kbd></button><div className="touch-controls" role="group" aria-label="角色移动">{[['w','↑','向前'],['a','←','向左'],['s','↓','向后'],['d','→','向右']].map(([key,arrow,label])=><button key={key} className={`move-${key}`} aria-label={label} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);touch.current.add(key)}} onPointerUp={()=>touch.current.delete(key)} onPointerCancel={()=>touch.current.delete(key)} onLostPointerCapture={()=>touch.current.delete(key)}>{arrow}</button>)}</div></>}</>
}
