'use client';
import { useEffect, useRef, useState } from 'react';
import projects from '../data/projects.json';
import World from './world';

type Message = {role:'user'|'assistant';content:string};
export default function Home(){
 const [selected,setSelected]=useState<number|null>(null),[catalog,setCatalog]=useState(false),[chat,setChat]=useState(false),[settings,setSettings]=useState(false),[visited,setVisited]=useState<number[]>([]),[messages,setMessages]=useState<Message[]>([]),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[endpoint,setEndpoint]=useState('/api/chat'),[token,setToken]=useState('');
 const end=useRef<HTMLDivElement>(null);
 useEffect(()=>{setEndpoint(localStorage.getItem('companion-endpoint')||'/api/chat')},[]);
 useEffect(()=>{end.current?.scrollIntoView({behavior:'smooth'})},[messages,busy,error]);
 useEffect(()=>{const f=(e:KeyboardEvent)=>{if(e.key==='Escape'){setSelected(null);setCatalog(false);setChat(false);setSettings(false)}};window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f)},[]);
 function open(i:number){setSelected(i);setVisited(v=>v.includes(i)?v:[...v,i]);setCatalog(false)}
 async function send(e:React.FormEvent){e.preventDefault();if(!input.trim()||busy)return;const next:Message[]=[...messages,{role:'user',content:input.trim()}];setMessages(next);setInput('');setBusy(true);setError('');try{const res=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify({messages:next.slice(-12)}),signal:AbortSignal.timeout(120000)});const data=await res.json() as {error?:string;reply?:unknown};if(!res.ok)throw Error(data.error||'连接失败');if(typeof data.reply!=='string')throw Error('连接服务返回格式错误');setMessages([...next,{role:'assistant',content:data.reply}])}catch(e){setError(e instanceof Error?e.message:'连接失败')}finally{setBusy(false)}}
 return <main>
 <World onSelect={open} onChat={()=>setChat(true)} paused={selected!==null||catalog||chat||settings}/>
 <header className="topbar"><a className="brand" href="/">✦ <span>GENIUSQI<small>THE PERSONAL WORLD</small></span></a><nav><button onClick={()=>setCatalog(true)}>作品图鉴 <span>{projects.length.toString().padStart(2,'0')}</span></button><a href="https://github.com/Smashwinny" target="_blank" rel="noreferrer">GitHub ↗</a><button aria-label="连接设置" onClick={()=>setSettings(true)}>⚙</button></nav></header>
 <section className="intro"><p className="eyebrow">A SMALL WORLD, BUILT WITH CURIOSITY</p><h1>把想法，<br/>变成一个世界<span>。</span></h1><p>欢迎来到我的创作浮岛。<br/>四处走走，遇见代码背后的作品。</p><button className="text-button" onClick={()=>setCatalog(true)}>探索我的作品 <span>↗</span></button></section>
 <div className="coordinates"><span className="live-dot"/> 创作浮岛 · EXPLORER MODE <small>已发现 {visited.length} / {projects.length}</small></div>
 <footer className="controls"><span><kbd>W A S D</kbd> 移动</span><span>拖动 · 环顾</span><span><kbd>E</kbd> 互动 / 点击展台</span><button onClick={()=>setCatalog(true)}>打开图鉴 ↗</button></footer>
 <button className="companion" onClick={()=>setChat(true)}><span className="companion-icon">✧</span><span>小星<small>你的浮岛向导 · 点击对话</small></span><b>↗</b></button>
 {selected!==null&&<div className="overlay" onClick={()=>setSelected(null)}><section className="panel project-panel" role="dialog" aria-modal="true" aria-label="作品详情" onClick={e=>e.stopPropagation()}><button className="close" autoFocus onClick={()=>setSelected(null)} aria-label="关闭">×</button><p className="eyebrow">DISCOVERY / {String(selected+1).padStart(2,'0')}</p><div className="project-symbol">{['⌘','◈','◎','✦'][selected%4]}</div><p className="tag">{projects[selected].language} · 非 Fork 仓库</p><h2>{projects[selected].name}</h2><p className="description">{projects[selected].description}</p><a className="primary" href={projects[selected].url} target="_blank" rel="noreferrer">在 GitHub 查看作品 ↗</a><button className="text-button" onClick={()=>{setInput(`介绍一下 ${projects[selected].name} 这个作品`);setSelected(null);setChat(true)}}>让小星介绍这个作品 →</button></section></div>}
 {catalog&&<div className="overlay" onClick={()=>setCatalog(false)}><section className="panel catalog" role="dialog" aria-modal="true" aria-label="作品图鉴" onClick={e=>e.stopPropagation()}><button className="close" autoFocus onClick={()=>setCatalog(false)}>×</button><p className="eyebrow">COLLECTION / SMASHWINNY</p><h2>作品图鉴<span className="muted"> / {projects.length}</span></h2><p>每一个展台，都是一个想法落地的地方。</p><div className="project-grid">{projects.map((p,i)=><button key={p.name} onClick={()=>open(i)}><small>{String(i+1).padStart(2,'0')} / {p.language}</small><strong>{p.name}</strong><span>{p.description}</span><em>{visited.includes(i)?'已发现':'查看作品'} ↗</em></button>)}</div></section></div>}
 {chat&&<aside className="chat panel" role="dialog" aria-label="与小星对话"><button className="close" autoFocus onClick={()=>setChat(false)}>×</button><p className="eyebrow">YOUR TRAVEL COMPANION</p><h2>✧ 小星</h2><p className="chat-subtitle">和我聊聊这里的作品，或你的下一个想法。</p><div className="messages" aria-live="polite">{messages.length===0&&<div className="bubble assistant">你好，旅行者！我是小星。想先了解哪个作品？<small>回复由站主配置的本机 Codex 提供，连接成功后才会回答。</small></div>}{messages.map((m,i)=><div key={i} className={`bubble ${m.role}`}>{m.content}</div>)}{busy&&<div className="bubble assistant">小星正在思考…</div>}{error&&<p className="error" role="alert">{error}<button onClick={()=>setSettings(true)}>检查连接设置</button></p>}<div ref={end}/></div><form onSubmit={send}><input aria-label="对话消息" maxLength={4000} placeholder="和小星说点什么…" value={input} onChange={e=>setInput(e.target.value)}/><button disabled={busy||!input.trim()} aria-label="发送消息">↑</button></form></aside>}
 {settings&&<div className="overlay" onClick={()=>setSettings(false)}><section className="panel settings" role="dialog" aria-modal="true" aria-label="连接设置" onClick={e=>e.stopPropagation()}><button className="close" autoFocus onClick={()=>setSettings(false)}>×</button><p className="eyebrow">COMPANION CONNECTION</p><h2>连接你的 Codex</h2><p>使用站点默认连接，或填写你配置的 HTTPS 连接服务地址。地址只保存在这台浏览器。</p><label>对话接口<input value={endpoint} onChange={e=>setEndpoint(e.target.value)} placeholder="/api/chat"/></label><label>访问口令（仅本次页面有效）<input type="password" value={token} onChange={e=>setToken(e.target.value)} autoComplete="off"/></label><button className="primary" onClick={()=>{try{const u=new URL(endpoint,location.origin);if(u.protocol!=='https:'&&u.origin!==location.origin)throw Error();localStorage.setItem('companion-endpoint',endpoint);setSettings(false)}catch{alert('请使用同站地址或 HTTPS 地址')}}}>保存连接</button><small>本机连接服务需要单独启动；这里不会保存你的 Codex 登录凭据。</small></section></div>}
 </main>
}
