'use client';
import { useEffect, useRef, useState } from 'react';
import projects from '../data/projects.json';
import World from './world-view';
import {preloadAvatar} from './scene/avatar-download.mjs';
import {worldStyles,validWorldStyle,type WorldStyle} from './scene/world-styles';
import {appearances,validAppearance,characterModels,validGender,type CharacterGender,type AppearanceId} from './scene/appearances';

type Message = {role:'user'|'assistant';content:string};
export default function Home(){
 const [selected,setSelected]=useState<number|null>(null),[catalog,setCatalog]=useState(false),[chat,setChat]=useState(false),[settings,setSettings]=useState(false),[visited,setVisited]=useState<number[]>([]),[messages,setMessages]=useState<Message[]>([]),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[endpoint,setEndpoint]=useState('/api/chat'),[token,setToken]=useState('');
 const [entered,setEntered]=useState(false),[worldRevision,setWorldRevision]=useState(0);
 const [style,setStyle]=useState<WorldStyle>('garden'),[styleMenu,setStyleMenu]=useState(false),[mistVisited,setMistVisited]=useState<string[]>([]);
 const conversationEpoch=useRef(0);
 const discovery=worldStyles.find(s=>s.id===style)!.discovery;
 const companionName=style==='elements'?'小浩':style==='mist'?'小津':'小齐';
 const catalogProjects=projects.map((project,index)=>({project,index})).filter(({project})=>!discovery||mistVisited.includes(project.name));
 useEffect(()=>{try{setStyle(validWorldStyle(localStorage.getItem('world-style')));const saved=JSON.parse(localStorage.getItem('mist-discoveries')||'[]');if(Array.isArray(saved))setMistVisited(saved.filter((v:unknown)=>typeof v==='string'&&projects.some(p=>p.name===v)))}catch{}},[]);
 function chooseStyle(next:WorldStyle){if(next==='garden'||next==='mist')preloadAvatar(playerSource);conversationEpoch.current++;setBusy(false);setEntered(true);if(next==='mist')setActor('player');setStyle(next);setStyleMenu(false);setSelected(null);setCatalog(false);setChat(false);setMessages([]);setError('');try{localStorage.setItem('world-style',next)}catch{}}
 const [wardrobe,setWardrobe]=useState(false),[actor,setActor]=useState<'player'|'companion'>('player');
 const [playerAppearance,setPlayerAppearance]=useState<AppearanceId>('original'),[companionAppearance,setCompanionAppearance]=useState<AppearanceId>('moon');
 const [playerGender,setPlayerGender]=useState<CharacterGender>('male'),[companionGender,setCompanionGender]=useState<CharacterGender>('female');
 const [playerSource,setPlayerSource]=useState<string>(characterModels.male),[companionSource,setCompanionSource]=useState<string>(characterModels.female),[modelError,setModelError]=useState('');
 const importedUrls=useRef<string[]>([]);
 useEffect(()=>{try{setPlayerAppearance(validAppearance(localStorage.getItem('player-appearance'),'original'));setCompanionAppearance(validAppearance(localStorage.getItem('companion-appearance'),'moon'));const player=validGender(localStorage.getItem('player-gender'),'male'),companion=validGender(localStorage.getItem('companion-gender'),'female');setPlayerGender(player);setPlayerSource(characterModels[player]);setCompanionGender(companion);setCompanionSource(characterModels[companion])}catch{}return()=>{importedUrls.current.forEach(url=>URL.revokeObjectURL(url))}},[]);
 function chooseGender(gender:CharacterGender){if((actor==='player'?playerSource:companionSource)===characterModels[gender])setWorldRevision(v=>v+1);if(actor==='player'){setPlayerGender(gender);setPlayerSource(characterModels[gender])}else{setCompanionGender(gender);setCompanionSource(characterModels[gender])}setModelError('');try{localStorage.setItem(`${actor}-gender`,gender)}catch{}}
 function chooseAppearance(id:AppearanceId){if(actor==='player')setPlayerAppearance(id);else setCompanionAppearance(id);try{localStorage.setItem(`${actor}-appearance`,id)}catch{}}
 async function importModel(file:File|undefined){
 if(!file)return;
 if(!file.name.toLowerCase().endsWith('.vrm')||file.size>30*1024*1024){setModelError('请选择不超过 30 MB 的 .vrm 人物文件');return}
 try{const bytes=await file.arrayBuffer(),view=new DataView(bytes);if(bytes.byteLength<20||view.getUint32(0,true)!==0x46546c67||view.getUint32(12,true)+20>bytes.byteLength)throw Error();const json=JSON.parse(new TextDecoder().decode(new Uint8Array(bytes,20,view.getUint32(12,true))));if(!json.extensions?.VRMC_vrm&&!json.extensions?.VRM)throw Error();if([...(json.buffers||[]),...(json.images||[])].some((r:{uri?:string})=>r.uri&&!r.uri.startsWith('data:')))throw Error('请使用贴图和数据已内嵌的独立 VRM 文件');
 const url=URL.createObjectURL(file);importedUrls.current.push(url);if(actor==='player')setPlayerSource(url);else setCompanionSource(url);setModelError('');setWardrobe(false)
 }catch(e){setModelError(e instanceof Error&&e.message.startsWith('请使用')?e.message:'文件不是有效的 VRM 人物，请重新选择')}
 }
 const end=useRef<HTMLDivElement>(null);
 useEffect(()=>{setEndpoint(localStorage.getItem('companion-endpoint')||'/api/chat')},[]);
 useEffect(()=>{end.current?.scrollIntoView({behavior:'smooth'})},[messages,busy,error]);
 useEffect(()=>{const f=(e:KeyboardEvent)=>{if(e.key==='Escape'){setSelected(null);setCatalog(false);setChat(false);setSettings(false);setWardrobe(false);setStyleMenu(false)}};window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f)},[]);
 function open(i:number){if(discovery){setMistVisited(v=>{const next=v.includes(projects[i].name)?v:[...v,projects[i].name];try{localStorage.setItem('mist-discoveries',JSON.stringify(next))}catch{}return next})}setSelected(i);setVisited(v=>v.includes(i)?v:[...v,i]);setCatalog(false)}
 async function send(e:React.FormEvent){e.preventDefault();if(!input.trim()||busy)return;const epoch=conversationEpoch.current;const next:Message[]=[...messages,{role:'user',content:input.trim()}];setMessages(next);setInput('');setBusy(true);setError('');try{const res=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify({messages:next.slice(-12),worldStyle:style,...(discovery?{discoveredProjects:mistVisited}:{})}),signal:AbortSignal.timeout(120000)});const data=await res.json() as {error?:string;reply?:unknown};if(!res.ok)throw Error(data.error||'连接失败');if(typeof data.reply!=='string')throw Error('连接服务返回格式错误');if(epoch===conversationEpoch.current)setMessages([...next,{role:'assistant',content:data.reply}])}catch(e){if(epoch===conversationEpoch.current)setError(e instanceof Error?e.message:'连接失败')}finally{if(epoch===conversationEpoch.current)setBusy(false)}}
 return <main data-world-style={style}>
 {entered&&<World key={worldRevision} style={style} onSelect={open} onChat={()=>setChat(true)} paused={selected!==null||catalog||chat||settings||wardrobe||styleMenu} chatOpen={chat} playerAppearance={playerAppearance} companionAppearance={companionAppearance} playerSource={playerSource} companionSource={companionSource}/>}
 <header className="topbar"><a className="brand" href="/">✦ <span>GENIUSQI<small>THE PERSONAL WORLD</small></span></a><nav><button onClick={()=>setStyleMenu(true)}>切换风格</button>{!['elements','mario'].includes(style)&&<button onClick={()=>setWardrobe(true)}>角色形象</button>}<button onClick={()=>setCatalog(true)}>{discovery?'发现手记':'作品图鉴'} {!discovery&&<span>{projects.length.toString().padStart(2,'0')}</span>}</button><a href="https://github.com/Smashwinny" target="_blank" rel="noreferrer">GitHub ↗</a><button aria-label="连接设置" onClick={()=>setSettings(true)}>⚙</button></nav></header>
 <section className="intro"><p className="eyebrow">{discovery?'BEYOND THE MIST':'A SMALL WORLD, BUILT WITH CURIOSITY'}</p>{discovery?<><h1>雾里有山，<br/>山外有路<span>。</span></h1><p>向前一跃，或循来路回望。<br/>有些岛藏着故事，有些只剩风声。</p></>:<><h1>把想法，<br/>变成一个世界<span>。</span></h1><p>欢迎来到我的创作浮岛。<br/>四处走走，遇见代码背后的作品。</p></>}<button className="text-button" onClick={()=>setCatalog(true)}>{discovery?'翻阅发现手记':'探索我的作品'} <span>↗</span></button></section>
 <div className="coordinates"><span className="live-dot"/> {discovery?'雾隐山海 · 前路未明':'创作浮岛 · EXPLORER MODE'} <small>{discovery?'只记来时路，不问终点。':`已发现 ${visited.length} / ${projects.length}`}</small></div>
 <footer className="controls"><span><kbd>W A S D</kbd> 移动</span><span><kbd>Space</kbd> {style==='garden'||style==='mist'?'跳跃 · 空中再按二段跳':'跳跃'}</span><span>拖动 · 环顾</span><span><kbd>E</kbd> {discovery?'调查石碑':'互动 / 点击展台'}</span><button onClick={()=>setCatalog(true)}>{discovery?'发现手记':'打开图鉴'} ↗</button></footer>
 <button className="companion" onClick={()=>setChat(true)}><span className="companion-icon">✧</span><span>{companionName}<small>{style==='elements'?'元素向导 · 点击对话':discovery?'传音向导 · 点击对话':'你的浮岛向导 · 点击对话'}</small></span><b>↗</b></button>
 {selected!==null&&<div className="overlay" onClick={()=>setSelected(null)}><section className="panel project-panel" role="dialog" aria-modal="true" aria-label="作品详情" onClick={e=>e.stopPropagation()}><button className="close" autoFocus onClick={()=>setSelected(null)} aria-label="关闭">×</button><p className="eyebrow">{discovery?'雾中拾遗':`DISCOVERY / ${String(selected+1).padStart(2,'0')}`}</p><div className="project-symbol">{['⌘','◈','◎','✦'][selected%4]}</div><p className="tag">{projects[selected].language} · 非 Fork 仓库</p><h2>{projects[selected].name}</h2><p className="description">{projects[selected].description}</p><a className="primary" href={projects[selected].url} target="_blank" rel="noreferrer">在 GitHub 查看作品 ↗</a><button className="text-button" onClick={()=>{setInput(`介绍一下 ${projects[selected].name} 这个作品`);setSelected(null);setChat(true)}}>让{companionName}介绍这个作品 →</button></section></div>}
 {catalog&&<div className="overlay" onClick={()=>setCatalog(false)}><section className="panel catalog" role="dialog" aria-modal="true" aria-label="作品图鉴" onClick={e=>e.stopPropagation()}><button className="close" autoFocus onClick={()=>setCatalog(false)}>×</button><p className="eyebrow">COLLECTION / SMASHWINNY</p><h2>{discovery?'发现手记':'作品图鉴'}{!discovery&&<span className="muted"> / {projects.length}</span>}</h2><p>{discovery?'这里只记下你亲自发现的作品，未抵达的岛仍在雾中。':'每一个展台，都是一个想法落地的地方。'} <a href="/asset-credits.txt" target="_blank" rel="noreferrer">场景素材鸣谢 ↗</a></p>{discovery&&catalogProjects.length===0&&<div className="empty-journal"><span>◎</span><p>手记还是空白。<br/>走近岛上的石碑，看看它留下了什么。</p><button className="primary" onClick={()=>setCatalog(false)}>回到雾中探索</button></div>}<div className="project-grid">{catalogProjects.map(({project:p,index:i})=><button key={p.name} onClick={()=>open(i)}><small>{!discovery&&`${String(i+1).padStart(2,'0')} / `}{p.language}</small><strong>{p.name}</strong><span>{p.description}</span><em>{discovery||visited.includes(i)?'已发现':'查看作品'} ↗</em></button>)}</div></section></div>}
 {chat&&<aside className="chat panel" role="dialog" aria-label={`与${companionName}对话`}><button className="close" autoFocus onClick={()=>setChat(false)}>×</button><p className="eyebrow">YOUR TRAVEL COMPANION</p><h2>✧ {companionName}</h2><p className="chat-subtitle">和我聊聊这里的作品，或你的下一个想法。</p><div className="messages" aria-live="polite">{messages.length===0&&<div className="bubble assistant">你好，旅行者！我是{companionName}。想先了解哪个作品？<small>回复由站主配置的本机 Codex 提供，连接成功后才会回答。</small></div>}{messages.map((m,i)=><div key={i} className={`bubble ${m.role}`}>{m.content}</div>)}{busy&&<div className="bubble assistant">{companionName}正在思考…</div>}{error&&<p className="error" role="alert">{error}<button onClick={()=>setSettings(true)}>检查连接设置</button></p>}<div ref={end}/></div><form onSubmit={send}><input aria-label="对话消息" maxLength={4000} placeholder={`和${companionName}说点什么…`} value={input} onChange={e=>setInput(e.target.value)}/><button disabled={busy||!input.trim()} aria-label="发送消息">↑</button></form></aside>}
 {wardrobe&&<div className="overlay" onClick={()=>setWardrobe(false)}><section className="panel wardrobe" role="dialog" aria-modal="true" aria-label="角色形象" onClick={e=>e.stopPropagation()}><button className="close" aria-label="关闭角色选择" autoFocus onClick={()=>setWardrobe(false)}>×</button><p className="eyebrow">CHARACTER STUDIO</p><h2>选择你的角色形象</h2><div className="actor-tabs" role="group" aria-label="更换对象"><button aria-pressed={actor==='player'} onClick={()=>setActor('player')}>旅行者</button>{!discovery&&<button aria-pressed={actor==='companion'} onClick={()=>setActor('companion')}>伙伴 · 小齐</button>}</div><p className="eyebrow">人物性别</p><div className="actor-tabs gender-tabs" role="group" aria-label="人物性别">{([["male","男角色"],["female","女角色"]] as const).map(([gender,label])=><button key={gender} aria-pressed={(actor==='player'?playerSource:companionSource)===characterModels[gender]} onClick={()=>chooseGender(gender)}>{label}</button>)}</div>{(actor==='player'?playerSource:companionSource).startsWith('blob:')&&<p className="wardrobe-note">当前使用你导入的人物。选择性别可切换回内置人物。</p>}<p className="eyebrow">配色与配饰</p><div className="appearance-grid">{appearances.map(p=><button key={p.id} aria-pressed={(actor==='player'?playerAppearance:companionAppearance)===p.id} onClick={()=>chooseAppearance(p.id)}><span className="appearance-swatch" style={{background:`linear-gradient(135deg,${p.hair||'#74523c'} 0 48%,${p.cloth||'#c5bfc9'} 48%)`}}>✧</span><strong>{p.name}</strong><small>{p.description}</small></button>)}</div><p className="wardrobe-note">男女角色使用不同人物模型；旅行者和{companionName}可分别选择，配色与配饰自由搭配。性别和配色选择会保存在本机浏览器。{discovery&&`当前世界为旅行者手持金箍棒，${companionName}通过传音对话。`}</p><label className="model-import">换成自己的 VRM 人物<input type="file" accept=".vrm" onChange={e=>{importModel(e.target.files?.[0]);e.target.value=''}}/></label><small>文件只在本机页面使用，不上传；导入后重新进入浮岛，刷新后恢复所选性别的内置人物。</small>{modelError&&<p role="alert" className="error">{modelError}</p>}<button className="text-button" onClick={()=>{chooseGender(actor==='player'?playerGender:companionGender);setWardrobe(false)}}>恢复所选性别的内置人物</button><button className="primary" onClick={()=>setWardrobe(false)}>回到浮岛查看</button></section></div>}
 {(styleMenu||(!entered&&!catalog&&!chat&&!settings&&!wardrobe))&&<div className={`overlay ${!entered?'world-entry':''}`} onClick={()=>setStyleMenu(false)}><section className="panel style-panel" role="dialog" aria-modal="true" aria-label="世界风格" onClick={e=>e.stopPropagation()}>{entered&&<button className="close" autoFocus aria-label="关闭风格选择" onClick={()=>setStyleMenu(false)}>×</button>}<p className="eyebrow">GENIUSQI / CHOOSE YOUR WORLD</p><h2>{entered?'同一段旅途，不同的天地。':'先选一重天地，再出发。'}</h2><p>{entered?'你熟悉的浮岛一直都在。':'晴空下漫游，或走进雾中的山海。'}</p><div className="style-options">{worldStyles.map(option=><button key={option.id} className={`style-card style-card-${option.id}`} aria-pressed={style===option.id} onClick={()=>chooseStyle(option.id)}><span className="style-landscape" aria-hidden="true"><i/><i/><i/></span><strong>{option.name}</strong><span>{option.reference}</span><small>{option.description}</small><em>{entered&&style===option.id?'当前风格':'进入这重天地 →'}</em></button>)}</div><small>{entered?'切换会回到该风格的起点；角色选择与发现手记会保留。':'选择后才载入这重天地。你也可以先浏览作品。'}</small>{!entered&&<button className="text-button" onClick={()=>setCatalog(true)}>{discovery?'先看发现手记 →':'先看作品图鉴 →'}</button>}</section></div>}
 {settings&&<div className="overlay" onClick={()=>setSettings(false)}><section className="panel settings" role="dialog" aria-modal="true" aria-label="连接设置" onClick={e=>e.stopPropagation()}><button className="close" autoFocus onClick={()=>setSettings(false)}>×</button><p className="eyebrow">COMPANION CONNECTION</p><h2>连接你的 Codex</h2><p>使用站点默认连接，或填写你配置的 HTTPS 连接服务地址。地址只保存在这台浏览器。</p><label>对话接口<input value={endpoint} onChange={e=>setEndpoint(e.target.value)} placeholder="/api/chat"/></label><label>访问口令（仅本次页面有效）<input type="password" value={token} onChange={e=>setToken(e.target.value)} autoComplete="off"/></label><button className="primary" onClick={()=>{try{const u=new URL(endpoint,location.origin);if(u.protocol!=='https:'&&u.origin!==location.origin)throw Error();localStorage.setItem('companion-endpoint',endpoint);setSettings(false)}catch{alert('请使用同站地址或 HTTPS 地址')}}}>保存连接</button><small>本机连接服务需要单独启动；这里不会保存你的 Codex 登录凭据。</small></section></div>}
 </main>
}
