'use client';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import projects from '../data/projects.json';
export default function World({onSelect,onChat,paused}:{onSelect:(n:number)=>void;onChat:()=>void;paused:boolean}){
 const host=useRef<HTMLDivElement>(null), callbacks=useRef({onSelect,onChat,paused});const [failed,setFailed]=useState(false),[near,setNear]=useState('');callbacks.current={onSelect,onChat,paused};
 useEffect(()=>{
 const el=host.current!;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true})}catch{setFailed(true);return}
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;el.appendChild(renderer.domElement);
 const scene=new THREE.Scene();scene.fog=new THREE.Fog('#b4ced2',32,85);const camera=new THREE.PerspectiveCamera(43,1,.1,180);const target=new THREE.Vector3(0,0,1);let yaw=.28, pitch=.64, distance=28;
 scene.add(new THREE.HemisphereLight('#e6f7ff','#719184',2.6));const sun=new THREE.DirectionalLight('#fff4d5',3.3);sun.position.set(-12,23,9);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-23,right:23,top:23,bottom:-23});scene.add(sun);
 const interact:THREE.Object3D[]=[];const floats:THREE.Object3D[]=[];
 function mesh(g:THREE.BufferGeometry,color:string,x:number,y:number,z:number,parent:THREE.Object3D=scene){const o=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color,roughness:.85,flatShading:true}));o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
 const cylinder=(a:number,b:number,h:number,n=8)=>new THREE.CylinderGeometry(a,b,h,n);
 mesh(cylinder(11,9.7,1.2,11),'#809b72',0,-.75,0);mesh(cylinder(9.7,5,5,11),'#657773',0,-3.8,0);mesh(cylinder(5,.8,3,9),'#566965',0,-7.6,0);mesh(cylinder(4.9,5,.12,40),'#d4c7a7',0,-.07,0);mesh(new THREE.TorusGeometry(4.5,.045,6,64),'#ece2c6',0,.02,0).rotation.x=Math.PI/2;
 // Warm stone paths between the central plaza and each exhibit.
 projects.forEach((p,i)=>{const a=i/projects.length*Math.PI*2,x=Math.sin(a)*7,z=Math.cos(a)*7;for(let j=0;j<3;j++){const step=mesh(new THREE.BoxGeometry(.65,.08,.55),'#c9c5aa',Math.sin(a)*(5+j*.5),0,Math.cos(a)*(5+j*.5));step.rotation.y=a}
 const stand=new THREE.Group();stand.position.set(x,0,z);scene.add(stand);mesh(cylinder(.85,1.1,.5),'#e4dac2',0,.2,0,stand);mesh(cylinder(.75,.85,.15),'#fff0cc',0,.53,0,stand);const color=['#e8b876','#8ababb','#a4a9df','#dbadbd'][i%4];const artifact=mesh(i%2?new THREE.OctahedronGeometry(.6):new THREE.BoxGeometry(.8,.8,.8),color,0,1.5,0,stand);artifact.userData.index=i;floats.push(artifact);interact.push(artifact);const halo=mesh(new THREE.TorusGeometry(.9,.028,6,36),'#fff1c2',0,1.5,0,stand);halo.rotation.x=.6;halo.userData.index=i;interact.push(halo);
 const canvas=document.createElement('canvas');canvas.width=512;canvas.height=128;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#1f3937';ctx.fillRect(0,0,512,128);ctx.fillStyle='#f3e8cb';ctx.font='bold 28px sans-serif';ctx.textAlign='center';ctx.fillText(p.name,256,58);ctx.font='20px sans-serif';ctx.fillStyle='#a5c0b0';ctx.fillText(`${String(i+1).padStart(2,'0')}  /  ${p.language}`,256,98);const tex=new THREE.CanvasTexture(canvas);const label=new THREE.Sprite(new THREE.SpriteMaterial({map:tex}));label.position.set(x,2.9,z);label.scale.set(3.2,.8,1);label.userData.index=i;scene.add(label);interact.push(label);
 });
 function tree(x:number,z:number,s:number){const g=new THREE.Group();g.position.set(x,0,z);g.scale.setScalar(s);scene.add(g);mesh(cylinder(.15,.23,1.7,6),'#736c4d',0,.7,0,g);mesh(new THREE.IcosahedronGeometry(1,0),'#66846a',0,2,0,g);mesh(new THREE.IcosahedronGeometry(.75,0),'#92a37a',.5,2.4,.1,g);mesh(new THREE.IcosahedronGeometry(.75,0),'#789573',-.5,2.5,-.1,g)}
 for(let i=0;i<19;i++){const a=i*2.399;tree(Math.cos(a)*9.7,Math.sin(a)*9.7,.65+(i%3)*.16)}
 for(let i=0;i<45;i++){const a=i*2.399,r=8.5+(i%4)*.35;mesh(new THREE.DodecahedronGeometry(.12+(i%3)*.06),'#b4bba0',Math.cos(a)*r,.08,Math.sin(a)*r)}
 // A small traveler and an original floating star companion.
 const player=new THREE.Group();scene.add(player);player.position.set(0,0,3);mesh(cylinder(.24,.36,.8),'#e6cba2',0,.7,0,player);mesh(new THREE.SphereGeometry(.24,12,8),'#efdfbf',0,1.3,0,player);mesh(new THREE.ConeGeometry(.39,.35,8),'#365e63',0,1.55,0,player);mesh(new THREE.BoxGeometry(.42,.55,.18),'#426e73',0,.8,.25,player);for(const x of [-.15,.15])mesh(new THREE.BoxGeometry(.15,.34,.18),'#4b5957',x,.2,0,player);
 const companion=new THREE.Group();scene.add(companion);const star=mesh(new THREE.OctahedronGeometry(.3),'#fff1c5',0,0,0,companion);star.userData.chat=true;interact.push(star);const ring=mesh(new THREE.TorusGeometry(.44,.026,8,32),'#fff6dc',0,0,0,companion);ring.rotation.x=1.1;ring.userData.chat=true;interact.push(ring);
 for(let i=0;i<10;i++){const a=i*2.4;const g=new THREE.Group();g.position.set(Math.sin(a)*(24+i),-4-i%3,Math.cos(a)*(24+i));scene.add(g);mesh(cylinder(2+i%3,.2,5,7),'#8aaba6',0,0,0,g);mesh(cylinder(2+i%3,2+i%3,.3,7),'#a3b39b',0,2.6,0,g)}
 const keys=new Set<string>(),ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let nearest=-1,frame=0,last=performance.now(),down:{x:number;y:number}|null=null,dragged=false;
 function select(){if(nearest>=0)callbacks.current.onSelect(nearest)}
 const keydown=(e:KeyboardEvent)=>{if(callbacks.current.paused||/INPUT|TEXTAREA/.test((e.target as HTMLElement).tagName))return;if(['w','a','s','d','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','e'].includes(e.key)){e.preventDefault();keys.add(e.key);if(e.key==='e')select()}};const keyup=(e:KeyboardEvent)=>keys.delete(e.key);const clear=()=>keys.clear();
 const start=(e:PointerEvent)=>{down={x:e.clientX,y:e.clientY};dragged=false;renderer.domElement.setPointerCapture(e.pointerId)};
 const move=(e:PointerEvent)=>{if(!down||callbacks.current.paused)return;const dx=e.clientX-down.x,dy=e.clientY-down.y;if(Math.abs(dx)+Math.abs(dy)>3)dragged=true;if(dragged){yaw-=dx*.006;pitch=THREE.MathUtils.clamp(pitch+dy*.003,.25,1.05)}down={x:e.clientX,y:e.clientY}};
 const stop=(e:PointerEvent)=>{down=null;if(dragged||callbacks.current.paused)return;const rect=el.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(interact)[0];if(hit){if(hit.object.userData.chat)callbacks.current.onChat();else callbacks.current.onSelect(hit.object.userData.index)}};
 const wheel=(e:WheelEvent)=>{if(!callbacks.current.paused){distance=THREE.MathUtils.clamp(distance+e.deltaY*.015,16,38)}};
 function resize(){renderer.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix()}const observer=new ResizeObserver(resize);observer.observe(el);resize();
 window.addEventListener('keydown',keydown);window.addEventListener('keyup',keyup);window.addEventListener('blur',clear);renderer.domElement.addEventListener('pointerdown',start);renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointerup',stop);renderer.domElement.addEventListener('wheel',wheel,{passive:true});
 function loop(now:number){const dt=Math.min((now-last)/1000,.05);last=now;const t=now/1000;if(!callbacks.current.paused){const x=Number(keys.has('d')||keys.has('ArrowRight'))-Number(keys.has('a')||keys.has('ArrowLeft')),z=Number(keys.has('s')||keys.has('ArrowDown'))-Number(keys.has('w')||keys.has('ArrowUp'));if(x||z){const v=new THREE.Vector3(x,0,z).normalize().applyAxisAngle(new THREE.Vector3(0,1,0),yaw);player.position.addScaledVector(v,dt*3.6);if(player.position.length()>9)player.position.setLength(9);player.rotation.y=Math.atan2(v.x,v.z)}}
 target.lerp(new THREE.Vector3(player.position.x*.35,0,player.position.z*.35),dt*2);camera.position.set(target.x+Math.sin(yaw)*Math.cos(pitch)*distance,target.y+Math.sin(pitch)*distance,target.z+Math.cos(yaw)*Math.cos(pitch)*distance);camera.lookAt(target);floats.forEach((o,i)=>{o.position.y=1.5+Math.sin(t*1.4+i)*.15;o.rotation.y=t*.25+i});companion.position.copy(player.position).add(new THREE.Vector3(1,1.9+Math.sin(t*2)*.18,.1));companion.rotation.y=t*.5;
 let n=-1,best=2.4;projects.forEach((_,i)=>{const a=i/projects.length*Math.PI*2,d=Math.hypot(player.position.x-Math.sin(a)*7,player.position.z-Math.cos(a)*7);if(d<best){best=d;n=i}});if(n!==nearest){nearest=n;setNear(n<0?'':projects[n].name)}renderer.render(scene,camera);frame=requestAnimationFrame(loop)}frame=requestAnimationFrame(loop);
 return()=>{cancelAnimationFrame(frame);observer.disconnect();window.removeEventListener('keydown',keydown);window.removeEventListener('keyup',keyup);window.removeEventListener('blur',clear);renderer.domElement.removeEventListener('pointerdown',start);renderer.domElement.removeEventListener('pointermove',move);renderer.domElement.removeEventListener('pointerup',stop);renderer.domElement.removeEventListener('wheel',wheel);scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose())}if(o instanceof THREE.Sprite){o.material.map?.dispose();o.material.dispose()}});renderer.dispose();renderer.domElement.remove()};
 },[]);
 return <><div className="world" ref={host} aria-label="可交互的三维作品浮岛"/>{failed&&<div className="webgl-error">设备暂不支持 3D 场景，请通过「作品图鉴」浏览全部作品。</div>}{near&&!paused&&<div className="near-prompt"><kbd>E</kbd> 查看 {near}</div>}</>
}
