'use client';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {Sky} from 'three/addons/objects/Sky.js';
import projects from '../data/projects.json';
import {buildEnvironment,exhibitPosition,groundHeight,islandRadius} from './scene/environment';
import {loadCharacter,type Character} from './scene/characters';
import {createCollisionWorld,PlayerController,safeCameraPosition,resolveFlyingBody} from './scene/physics.mjs';
import type {AppearanceId} from './scene/appearances';

export default function World({onSelect,onChat,paused,chatOpen,playerAppearance,companionAppearance,playerSource,companionSource}:{onSelect:(n:number)=>void;onChat:()=>void;paused:boolean;chatOpen:boolean;playerAppearance:AppearanceId;companionAppearance:AppearanceId;playerSource:string;companionSource:string}){
 const host=useRef<HTMLDivElement>(null),touchKeys=useRef(new Set<string>()),jumpQueued=useRef(false),callbacks=useRef({onSelect,onChat,paused,chatOpen,playerAppearance,companionAppearance});
 const [failed,setFailed]=useState(false),[near,setNear]=useState(-1),[progress,setProgress]=useState(0),[warning,setWarning]=useState('');
 const viewMode=useRef<'explore'|'overview'>('explore');const [overview,setOverview]=useState(false);
 callbacks.current={onSelect,onChat,paused,chatOpen,playerAppearance,companionAppearance};useEffect(()=>{if(paused){touchKeys.current.clear();jumpQueued.current=false}},[paused]);
 useEffect(()=>{
 setProgress(0);setWarning('');setNear(-1);setFailed(false);
 const el=host.current!;let renderer:THREE.WebGLRenderer;
 try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'})}catch{setFailed(true);return}
 let renderScale=Math.min(devicePixelRatio,1);renderer.setPixelRatio(renderScale);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;el.appendChild(renderer.domElement);
 const scene=new THREE.Scene();scene.background=new THREE.Color('#b9dce5');scene.fog=new THREE.FogExp2('#b9dce5',.009);
 const camera=new THREE.PerspectiveCamera(48,1,.1,350),target=new THREE.Vector3(0,1.1,7.5);let yaw=.1,pitch=.24,distance=7.5;
 const sky=new Sky();sky.scale.setScalar(300);scene.add(sky);const skyUniforms=sky.material.uniforms;skyUniforms.turbidity.value=3;skyUniforms.rayleigh.value=1.4;skyUniforms.mieCoefficient.value=.006;skyUniforms.mieDirectionalG.value=.8;skyUniforms.sunPosition.value.set(-.5,.55,-.3);
 scene.add(new THREE.HemisphereLight('#d6efff','#596c38',2));const sun=new THREE.DirectionalLight('#fff1d0',2.7);sun.position.set(-18,32,14);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-28,right:28,top:28,bottom:-28,near:.5,far:85});sun.shadow.normalBias=.055;sun.shadow.bias=-.0001;scene.add(sun);
 const player=new THREE.Group();player.position.set(0,groundHeight(0,7.5),7.5);scene.add(player);const companion=new THREE.Group();scene.add(companion);
 let avatar:Character|undefined,fairy:Character|undefined,environment:Awaited<ReturnType<typeof buildEnvironment>>|undefined,disposed=false,ready=false,sceneryWarned=false;
 const collisionRoot=new THREE.Group();let controller:PlayerController|undefined;let collisionWorld:ReturnType<typeof createCollisionWorld>|undefined;
 const interact:THREE.Object3D[]=[];const artifacts:THREE.Group[]=[];const signs:THREE.Sprite[]=[];const spots=projects.map((_,i)=>exhibitPosition(i,projects.length));
 const stone=new THREE.MeshStandardMaterial({color:'#e4deca',roughness:.85}),gold=new THREE.MeshStandardMaterial({color:'#c5a367',metalness:.6,roughness:.35});
 function mesh(g:THREE.BufferGeometry,m:THREE.Material,x:number,y:number,z:number,parent:THREE.Object3D){const o=new THREE.Mesh(g,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
 function label(text:string,index:number){const canvas=document.createElement('canvas');canvas.width=640;canvas.height=128;const c=canvas.getContext('2d')!;c.fillStyle='#233e37d9';c.beginPath();c.roundRect(0,0,640,128,24);c.fill();c.fillStyle='#f3e6c8';c.font='500 31px sans-serif';c.textAlign='center';c.fillText(text,320,55);c.font='20px sans-serif';c.fillStyle='#c0cfae';c.fillText(`${String(index+1).padStart(2,'0')}  ·  走近探索`,320,95);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,depthTest:false,transparent:true}));sprite.scale.set(2.6,.52,1);sprite.userData.index=index;return sprite}
 projects.forEach((project,i)=>{
 const stand=new THREE.Group();stand.position.copy(spots[i]);scene.add(stand);for(let l=0;l<3;l++)mesh(new THREE.CylinderGeometry(.75-l*.08,.79-l*.08,.14,48),stone,0,l*.14+.07,0,stand);mesh(new THREE.CylinderGeometry(.37,.48,.85,32),stone,0,.83,0,stand);mesh(new THREE.CylinderGeometry(.68,.56,.16,48),stone,0,1.34,0,stand);
 const artifact=new THREE.Group();artifact.position.y=2.05;stand.add(artifact);artifacts.push(artifact);const accent=new THREE.MeshStandardMaterial({color:['#5b949e','#ba7f61','#a39bbf','#77986f'][i%4],metalness:.25,roughness:.35});
 if(/terminal|codex|system/.test(project.name)){const screen=mesh(new THREE.BoxGeometry(.85,.6,.055),gold,0,0,0,artifact);const surface=mesh(new THREE.PlaneGeometry(.76,.5),new THREE.MeshStandardMaterial({color:'#16383b',emissive:'#2e7880',emissiveIntensity:.5}),0,0,.03,artifact);for(let j=0;j<4;j++)mesh(new THREE.BoxGeometry(.3+j*.08,.014,.008),new THREE.MeshBasicMaterial({color:'#a9e3bd'}),-.11,-.15+j*.1,.04,artifact);screen.rotation.y=.05;surface.rotation.y=.05}
 else if(/bill|reminder/.test(project.name)){mesh(new THREE.BoxGeometry(.42,.78,.065),accent,0,0,0,artifact);mesh(new THREE.PlaneGeometry(.35,.63),new THREE.MeshStandardMaterial({color:'#f0dec0',emissive:'#f0dec0',emissiveIntensity:.15}),0,.02,.034,artifact);for(let j=0;j<3;j++)mesh(new THREE.BoxGeometry(.25,.03,.01),gold,0,.16-j*.14,.045,artifact)}
 else {for(let j=0;j<3;j++){const ring=mesh(new THREE.TorusGeometry(.37+j*.07,.021,12,64),gold,0,0,0,artifact);ring.rotation.set(j*.8,.6,j*.9)}mesh(new THREE.IcosahedronGeometry(.23,3),accent,0,0,0,artifact)}
 stand.updateMatrixWorld(true);stand.traverse(o=>{if(o instanceof THREE.Mesh){o.userData.index=i;interact.push(o);if(o.parent===stand){const proxy=new THREE.Mesh(o.geometry,o.material);proxy.matrix.copy(o.matrixWorld);proxy.matrixAutoUpdate=false;collisionRoot.add(proxy)}}});const sign=label(project.name,i);sign.position.copy(spots[i]).add(new THREE.Vector3(0,3,0));scene.add(sign);interact.push(sign);signs.push(sign);
 });
 function disposeTree(root:THREE.Object3D){const geometry=new Set<THREE.BufferGeometry>(),materials=new Set<THREE.Material>(),textures=new Set<THREE.Texture>();root.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.Sprite||o instanceof THREE.Points){if(o instanceof THREE.Mesh||o instanceof THREE.Points)geometry.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material]){materials.add(m);for(const value of Object.values(m))if(value instanceof THREE.Texture)textures.add(value)}}});geometry.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose())}
 const stages={environment:0,player:0,companion:0};const report=(key:keyof typeof stages,value:number)=>{stages[key]=value;if(!disposed&&!ready)setProgress(Math.min(99,Math.floor(stages.environment*10+stages.player*90)))};
 const loading=[buildEnvironment(scene,v=>report('environment',v)).then(value=>{environment=value;if(disposed){value.dispose();disposeTree(value.root);scene.remove(value.root)}else if(value.missing)setWarning('部分景物加载失败，可刷新重试。')}),loadCharacter(false,playerSource,false,p=>report('player',p.phase==='download'?(p.total?p.loaded/p.total*.9:0):.95)).then(value=>{if(disposed){disposeTree(value.root);return}avatar=value;report('player',1);player.add(value.root)})];
 const loadCompanion=()=>loadCharacter(true,companionSource,false,p=>report('companion',p.phase==='download'?(p.total?p.loaded/p.total*.9:0):.95)).then(value=>{if(disposed){disposeTree(value.root);return}fairy=value;report('companion',1);companion.add(value.root);value.root.traverse(o=>{if(o instanceof THREE.Mesh){o.userData.chat=true;interact.push(o)}})}).catch(()=>{if(!disposed)setWarning('小齐暂未加载成功，仍可探索和通过聊天按钮交流。')});
 Promise.allSettled(loading).then(results=>{if(disposed)return;if(environment){collisionRoot.add(environment.collisionRoot);collisionWorld=createCollisionWorld(collisionRoot);controller=new PlayerController(collisionWorld,player.position);companion.position.copy(player.position).add(new THREE.Vector3(1.2,1.6,.2))}ready=true;setProgress(100);void loadCompanion();if(results.some(r=>r.status==='rejected'))setWarning('部分模型未能加载，请刷新重试；作品图鉴仍可使用。')});
 const keys=new Set<string>(),ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let frame=0,last=performance.now(),nearest=-1,down:{x:number;y:number;startX:number;startY:number}|null=null,dragged=false;
 const clear=()=>{keys.clear();touchKeys.current.clear();jumpQueued.current=false;down=null};
 const keydown=(e:KeyboardEvent)=>{if(callbacks.current.paused||/INPUT|TEXTAREA/.test((e.target as HTMLElement).tagName))return;const k=e.key.length===1?e.key.toLowerCase():e.key;if(k===' '&&!e.repeat){e.preventDefault();jumpQueued.current=true}if(['w','a','s','d','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','e'].includes(k)){e.preventDefault();keys.add(k);if(k==='e'&&nearest>=0)callbacks.current.onSelect(nearest)}};
 const keyup=(e:KeyboardEvent)=>keys.delete(e.key.length===1?e.key.toLowerCase():e.key);
 const start=(e:PointerEvent)=>{down={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY};dragged=false;renderer.domElement.setPointerCapture(e.pointerId)};
 const move=(e:PointerEvent)=>{if(!down||callbacks.current.paused)return;const dx=e.clientX-down.x,dy=e.clientY-down.y;if(Math.hypot(e.clientX-down.startX,e.clientY-down.startY)>4)dragged=true;if(dragged){yaw-=dx*.005;pitch=THREE.MathUtils.clamp(pitch+dy*.003,.06,1.05)}down.x=e.clientX;down.y=e.clientY};
 const stop=(e:PointerEvent)=>{down=null;if(dragged||callbacks.current.paused)return;const rect=el.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(interact)[0];if(hit){if(hit.object.userData.chat)callbacks.current.onChat();else callbacks.current.onSelect(hit.object.userData.index)}};
 const wheel=(e:WheelEvent)=>{if(!callbacks.current.paused){distance=THREE.MathUtils.clamp(distance+e.deltaY*.008,4,14)}};
 function resize(){renderer.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix()};const observer=new ResizeObserver(resize);observer.observe(el);resize();
 window.addEventListener('keydown',keydown);window.addEventListener('keyup',keyup);window.addEventListener('blur',clear);document.addEventListener('visibilitychange',clear);renderer.domElement.addEventListener('pointerdown',start);renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointerup',stop);renderer.domElement.addEventListener('pointercancel',clear);renderer.domElement.addEventListener('wheel',wheel,{passive:true});
 const direction=new THREE.Vector3(),followTarget=new THREE.Vector3(),desiredCamera=new THREE.Vector3();let lastPlayerAppearance='',lastCompanionAppearance='';let turn=0;
 const cameraRay=new THREE.Vector3(),flightVelocity=new THREE.Vector3();const lastFlightPosition=new THREE.Vector3();let lastPaused=false;
 let frameAverage=16.7,qualityChecked=performance.now();
 function loop(now:number){if(document.hidden){last=now;frame=requestAnimationFrame(loop);return}const elapsed=now-last;frameAverage=frameAverage*.98+elapsed*.02;if(ready&&now-qualityChecked>4000){if(frameAverage>25&&renderScale>.65){renderScale=Math.max(.65,renderScale-.15);renderer.setPixelRatio(renderScale);resize()}qualityChecked=now}const dt=Math.min((now-last)/1000,.08);last=now;const t=now/1000;
 const state=callbacks.current;
 if(state.paused&&!lastPaused){keys.clear();touchKeys.current.clear();jumpQueued.current=false}lastPaused=state.paused;
 if(avatar&&lastPlayerAppearance!==state.playerAppearance){avatar.setAppearance(state.playerAppearance);lastPlayerAppearance=state.playerAppearance}
 if(fairy&&lastCompanionAppearance!==state.companionAppearance){fairy.setAppearance(state.companionAppearance);lastCompanionAppearance=state.companionAppearance}
 direction.set(0,0,0);turn=0;
 if(ready&&controller&&!state.paused){const held=(key:string,arrow:string)=>keys.has(key)||keys.has(arrow)||touchKeys.current.has(key);direction.set(Number(held('d','ArrowRight'))-Number(held('a','ArrowLeft')),0,Number(held('s','ArrowDown'))-Number(held('w','ArrowUp'))).normalize().applyAxisAngle(new THREE.Vector3(0,1,0),yaw);
 if(direction.lengthSq()>.01){const heading=Math.atan2(direction.x,direction.z);turn=Math.atan2(Math.sin(heading-player.rotation.y),Math.cos(heading-player.rotation.y));player.rotation.y+=turn*(1-Math.exp(-10*dt))}
 if(jumpQueued.current){controller.requestJump();jumpQueued.current=false}player.position.copy(controller.update(dt,direction));
 if(Math.hypot(controller.velocity.x,controller.velocity.z)>.12){const heading=Math.atan2(controller.velocity.x,controller.velocity.z);const angle=Math.atan2(Math.sin(heading-player.rotation.y),Math.cos(heading-player.rotation.y));const rotation=THREE.MathUtils.clamp(angle,-dt*6,dt*6);player.rotation.y+=rotation;turn=rotation/Math.max(dt,.001)/6}
 }
 const speed=controller?Math.hypot(controller.velocity.x,controller.velocity.z)/3.1:0;
 avatar?.update(state.paused?0:dt,t,{speed:state.paused?0:speed,metersPerSecond:speed*3.1,grounded:controller?.grounded??true,verticalVelocity:controller?.velocity.y??0,landing:controller?.landing??0,turn,engaged:false});if(ready&&environment&&collisionWorld){const added=environment.update(t,player.position,viewMode.current==='overview');if(added.length){const batch=new THREE.Group();for(const mesh of added)batch.add(mesh);collisionWorld.subTrees.push(createCollisionWorld(batch))}}if(environment?.missing&&!sceneryWarned){sceneryWarned=true;setWarning('部分景物暂未加载成功，仍可继续探索。')}
 // Local shoulder offset follows heading; a critically damped spring gives flight inertia.
 followTarget.set(1.2+Math.sin(t*.8)*.12,1.45+Math.sin(t*2.2)*.13,.3+Math.sin(t*1.1)*.1).applyAxisAngle(new THREE.Vector3(0,1,0),player.rotation.y).add(player.position);
 lastFlightPosition.copy(companion.position);
 const flightSteps=Math.max(1,Math.ceil(dt/(1/120))),h=dt/flightSteps;
 for(let j=0;j<flightSteps;j++){flightVelocity.addScaledVector(cameraRay.copy(followTarget).sub(companion.position),h*24);flightVelocity.multiplyScalar(Math.exp(-9*h));companion.position.addScaledVector(flightVelocity,h);}
 if(collisionWorld&&fairy)companion.position.copy(resolveFlyingBody(collisionWorld,companion.position));
 const flightSpeed=Math.min(1,lastFlightPosition.distanceTo(companion.position)/Math.max(dt,.001)/3.1),flightHeading=state.chatOpen?Math.atan2(camera.position.x-companion.position.x,camera.position.z-companion.position.z):player.rotation.y;
 const bank=Math.atan2(Math.sin(flightHeading-companion.rotation.y),Math.cos(flightHeading-companion.rotation.y));companion.rotation.y+=bank*(1-Math.exp(-5*dt));
 fairy?.update(dt,t,{speed:flightSpeed,grounded:false,verticalVelocity:flightVelocity.y,landing:0,turn:bank,engaged:state.chatOpen});
 const wide=viewMode.current==='overview';followTarget.set(wide?0:player.position.x,wide?0:player.position.y+1.45,wide?0:player.position.z);target.lerp(followTarget,1-Math.exp(-6*dt));const d=wide?43:distance,p=wide?.64:pitch;desiredCamera.set(target.x+Math.sin(yaw)*Math.cos(p)*d,target.y+Math.sin(p)*d,target.z+Math.cos(yaw)*Math.cos(p)*d);camera.position.lerp(desiredCamera,1-Math.exp(-6*dt));if(collisionWorld&&!wide)camera.position.copy(safeCameraPosition(collisionWorld,target,camera.position));camera.lookAt(target);
 artifacts.forEach((o,i)=>{o.position.y=2.05+Math.sin(t*1.3+i)*.07;o.rotation.y=t*.2+i});let n=-1,best=2.4;spots.forEach((spot,i)=>{const d=Math.hypot(player.position.x-spot.x,player.position.z-spot.z);if(d<best){best=d;n=i}const opacity=wide?1:THREE.MathUtils.clamp(1-(d-5)/12,0,1);signs[i].material.opacity=opacity;signs[i].visible=opacity>.02});if(n!==nearest){nearest=n;setNear(n)}if(!document.hidden)renderer.render(scene,camera);frame=requestAnimationFrame(loop)
 }camera.position.set(0,3,15);frame=requestAnimationFrame(loop);
 return()=>{disposed=true;cancelAnimationFrame(frame);observer.disconnect();window.removeEventListener('keydown',keydown);window.removeEventListener('keyup',keyup);window.removeEventListener('blur',clear);document.removeEventListener('visibilitychange',clear);renderer.domElement.removeEventListener('pointerdown',start);renderer.domElement.removeEventListener('pointermove',move);renderer.domElement.removeEventListener('pointerup',stop);renderer.domElement.removeEventListener('pointercancel',clear);renderer.domElement.removeEventListener('wheel',wheel);environment?.dispose();disposeTree(scene);renderer.dispose();renderer.domElement.remove()};
 },[playerSource,companionSource]);
 return <><div className="world" ref={host} aria-label="可交互的三维作品浮岛"/>{failed?<div className="webgl-error">设备暂不支持 3D 场景，请通过「作品图鉴」浏览全部作品。</div>:<><button className="view-toggle" onClick={()=>{viewMode.current=overview?'explore':'overview';setOverview(!overview)}}>{overview?'返回人物视角':'俯瞰浮岛'} ⤢</button>{progress<100&&<div className="world-loading" role="status"><span>正在进入创作浮岛</span><div role="progressbar" aria-label="浮岛资源准备进度" aria-valuemin={0} aria-valuemax={100} aria-valuenow={progress}><i style={{width:`${progress}%`}}/></div><small>准备主角与地形，景物进入后分批展开 · {progress}%</small></div>}{warning&&<div className="asset-warning" role="status">{warning}</div>}</>}{near>=0&&!paused&&<button className="near-prompt" onClick={()=>onSelect(near)}><kbd>E</kbd> 查看 {projects[near].name}</button>}{!failed&&!paused&&<button className="jump-button" aria-label="跳跃，空中再按一次二段跳" title="空中再按一次，可二段跳" onClick={()=>{jumpQueued.current=true}}>二段跳 <kbd>Space</kbd></button>}{!failed&&!paused&&<div className="touch-controls" role="group" aria-label="角色移动">{[['w','↑','向前'],['a','←','向左'],['s','↓','向后'],['d','→','向右']].map(([key,arrow,label])=><button key={key} className={`move-${key}`} aria-label={label} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);touchKeys.current.add(key)}} onPointerUp={()=>touchKeys.current.delete(key)} onPointerCancel={()=>touchKeys.current.delete(key)} onLostPointerCapture={()=>touchKeys.current.delete(key)} onContextMenu={e=>e.preventDefault()}>{arrow}</button>)}</div>}</>
}
